In [2]:
import pandas as pd

In [12]:
df_list = []
for i in range(0,5):
    this_df = pd.read_csv(f'high_valuation/train_{i}.csv')
    df_list.append(this_df)
df = pd.concat(df_list)

In [14]:
df['type'] = 'TRAIN'

In [15]:
df.describe()

,close_day1,high_day1,low_day1,open_day1,vol_day1,VWAP_day1,ma7_day1,ma21_day1,26ema_day1,12ema_day1,...,dealer_buy_day20,foreign_buy_skew_day20,foreign_buy_kurtosis_day20,investment_buy_skew_day20,investment_buy_kurtosis_day20,dealer_buy_skew_day20,dealer_buy_kurtosis_day20,Y,StockNo,cluster
count,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,...,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06,1.169159e+06
mean,6.232777e-02,6.202933e-02,6.244851e-02,6.250605e-02,1.140494e-01,6.485818e-02,6.303254e-02,6.299753e-02,6.345146e-02,6.310659e-02,...,4.853722e-01,5.028338e-01,2.853182e-01,4.781891e-01,3.831163e-01,4.955301e-01,3.552433e-01,4.798304e-01,3.328496e+03,1.955174e+00
std,7.788620e-02,7.775821e-02,7.785230e-02,7.811119e-02,2.800140e-02,7.821230e-02,7.868667e-02,7.860323e-02,7.909995e-02,7.872829e-02,...,1.478784e-01,1.767890e-01,1.953632e-01,2.586946e-01,3.118512e-01,2.011638e-01,2.169894e-01,4.995932e-01,2.104197e+03,1.262355e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.101000e+03,0.000000e+00
25%,1.824959e-02,1.807393e-02,1.830509e-02,1.826764e-02,9.910278e-02,2.037774e-02,1.850303e-02,1.858024e-02,1.870794e-02,1.857008e-02,...,2.983881e-01,4.016264e-01,1.559173e-01,2.992239e-01,1.620724e-01,3.811983e-01,2.005041e-01,0.000000e+00,2.108000e+03,1.000000e+00
50%,3.851530e-02,3.821285e-02,3.865670e-02,3.863142e-02,1.104368e-01,4.140708e-02,3.898449e-02,3.895911e-02,3.924057e-02,3.902914e-02,...,4.678528e-01,5.006886e-01,2.239204e-01,5.000000e-01,3.055881e-01,5.000000e-01,2.921478e-01,0.000000e+00,2.501000e+03,2.000000e+00
75%,7.672048e-02,7.614684e-02,7.699563e-02,7.695087e-02,1.259247e-01,7.969319e-02,7.767064e-02,7.767203e-02,7.828177e-02,7.778867e-02,...,6.116771e-01,6.047857e-01,3.524065e-01,6.423747e-01,5.556963e-01,6.123444e-01,4.557260e-01,1.000000e+00,3.494000e+03,3.000000e+00
max,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.945000e+03,4.000000e+00

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1169159 entries, 0 to 140860
Columns: 585 entries, close_day1 to type
dtypes: float64(580), int64(3), object(2)
memory usage: 5.1+ GB

In [17]:
df2_list = []
for i in range(0,5):
    this_df = pd.read_csv(f'high_valuation/val_{i}.csv')
    df2_list.append(this_df)
df2 = pd.concat(df2_list)

In [18]:
df2['type'] = 'VALIDATE'

In [19]:
df2.describe()

,close_day1,high_day1,low_day1,open_day1,vol_day1,VWAP_day1,ma7_day1,ma21_day1,26ema_day1,12ema_day1,...,dealer_buy_day20,foreign_buy_skew_day20,foreign_buy_kurtosis_day20,investment_buy_skew_day20,investment_buy_kurtosis_day20,dealer_buy_skew_day20,dealer_buy_kurtosis_day20,Y,StockNo,cluster
count,196193.000000,196193.000000,196193.000000,196193.000000,196193.000000,196193.000000,196193.000000,196193.000000,196193.000000,196193.000000,...,196193.000000,1.961930e+05,196193.000000,1.961930e+05,196193.000000,196193.000000,196193.000000,196193.000000,196193.000000,196193.000000
mean,0.085735,0.085147,0.085989,0.085946,0.107911,0.088235,0.086494,0.086207,0.086708,0.086511,...,0.484856,5.123990e-01,0.240084,4.752647e-01,0.350912,0.511952,0.385328,0.491684,3666.372276,2.074009
std,0.105823,0.105461,0.105707,0.105900,0.022675,0.105814,0.106609,0.106142,0.106575,0.106525,...,0.141838,1.419568e-01,0.148211,2.584982e-01,0.340700,0.216129,0.222055,0.499932,2188.578911,1.274806
min,0.001011,0.000986,0.001015,0.001007,-0.026145,0.000000,0.001014,0.001028,0.001010,0.001021,...,0.132814,3.226233e-16,0.000000,-3.226233e-16,0.000000,0.000000,0.000000,0.000000,1101.000000,0.000000
25%,0.024391,0.024151,0.024575,0.024466,0.095664,0.026765,0.024568,0.024416,0.024578,0.024575,...,0.389511,4.295917e-01,0.146294,3.070180e-01,0.000000,0.378859,0.222164,0.000000,2324.000000,1.000000
50%,0.053058,0.052571,0.053321,0.053227,0.107963,0.056049,0.053573,0.053454,0.053712,0.053586,...,0.467853,5.125202e-01,0.196583,5.000000e-01,0.272426,0.517682,0.329373,0.000000,2881.000000,2.000000
75%,0.103793,0.103112,0.103983,0.104057,0.118891,0.106522,0.104520,0.103869,0.104267,0.104471,...,0.611677,5.951493e-01,0.284787,5.982352e-01,0.546204,0.651564,0.499636,1.000000,4919.000000,3.000000
max,1.615203,1.595316,1.590507,1.584507,0.653372,1.596170,1.614285,1.574782,1.581267,1.598085,...,1.173831,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,9945.000000,4.000000

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 196193 entries, 0 to 29343
Columns: 585 entries, close_day1 to type
dtypes: float64(580), int64(3), object(2)
memory usage: 877.1+ MB

In [21]:
df3_list = []
for i in range(0,5):
    this_df = pd.read_csv(f'high_valuation/test_{i}.csv')
    df3_list.append(this_df)
df3 = pd.concat(df3_list)

In [22]:
df3['type'] = 'TEST'

In [23]:
df3.describe()

,close_day1,high_day1,low_day1,open_day1,vol_day1,VWAP_day1,ma7_day1,ma21_day1,26ema_day1,12ema_day1,...,dealer_buy_day20,foreign_buy_skew_day20,foreign_buy_kurtosis_day20,investment_buy_skew_day20,investment_buy_kurtosis_day20,dealer_buy_skew_day20,dealer_buy_kurtosis_day20,Y,StockNo,cluster
count,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,...,259569.000000,2.595690e+05,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000,259569.000000
mean,0.095663,0.095013,0.095837,0.095946,0.109067,0.098106,0.096946,0.097465,0.098184,0.097291,...,0.470840,5.009417e-01,0.248805,0.480882,0.364745,0.510709,0.386869,0.482993,3740.051173,2.086362
std,0.119977,0.119387,0.119759,0.120188,0.027156,0.119721,0.121942,0.123208,0.124011,0.122531,...,0.138601,1.427296e-01,0.145572,0.265471,0.353111,0.218487,0.230907,0.499712,2215.446141,1.254713
min,0.001399,0.001399,0.001382,0.001386,-0.125823,0.000000,0.001432,0.001577,0.001569,0.001485,...,-0.098462,7.527878e-16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1101.000000,0.000000
25%,0.028518,0.028191,0.028726,0.028625,0.095503,0.031188,0.028843,0.028804,0.029014,0.028887,...,0.298360,4.143984e-01,0.153695,0.307299,0.000000,0.384710,0.215708,0.000000,2340.000000,1.000000
50%,0.056359,0.055818,0.056725,0.056557,0.107542,0.059489,0.056959,0.056823,0.057281,0.056950,...,0.467171,5.001413e-01,0.205560,0.500000,0.280420,0.515128,0.325674,0.000000,2888.000000,2.000000
75%,0.111604,0.111238,0.111642,0.112048,0.119937,0.114438,0.112871,0.113576,0.114446,0.113319,...,0.611677,5.870075e-01,0.297348,0.620284,0.604424,0.644897,0.504763,1.000000,4952.000000,3.000000
max,1.735590,1.714609,1.726560,1.723188,1.031159,1.723348,1.754488,1.735703,1.722641,1.741549,...,0.960715,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9958.000000,4.000000

In [24]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 259569 entries, 0 to 42048
Columns: 585 entries, close_day1 to type
dtypes: float64(580), int64(3), object(2)
memory usage: 1.1+ GB

In [25]:
df.columns

Index(['close_day1', 'high_day1', 'low_day1', 'open_day1', 'vol_day1',
       'VWAP_day1', 'ma7_day1', 'ma21_day1', '26ema_day1', '12ema_day1',
       ...
       'foreign_buy_kurtosis_day20', 'investment_buy_skew_day20',
       'investment_buy_kurtosis_day20', 'dealer_buy_skew_day20',
       'dealer_buy_kurtosis_day20', 'Y', 'ts', 'StockNo', 'cluster', 'type'],
      dtype='object', length=585)

In [26]:
df_complete = pd.concat([df,df2,df3])

In [ ]:
df_complete.describe()

In [28]:
df_complete.to_csv('high_val_cluster_complete.csv', index=False)

In [3]:
df_test = pd.read_csv(r'D:\OneDrive - SinoPac\training\train_large.csv')

In [4]:
df_test

,open_day1,high_day1,low_day1,close_day1,vol_day1,VWAP_day1,index_open_day1,index_high_day1,index_low_day1,index_close_day1,...,dealer_buy_kurtosis_day20,pvt_day20,ATR_day20,RSI_15_day20,SO5_day20,SO3_day20,Y,ts,StockNo,cluster
0,0.002263,0.002303,0.002237,0.002256,0.225242,0.003017,0.864141,0.856053,0.865558,0.860005,...,0.143095,0.355717,0.002299,0.027467,0.493005,0.495476,0,2007-09-06,1218,1
1,0.002259,0.002298,0.002232,0.002250,0.224382,0.003020,0.821859,0.825992,0.824660,0.822716,...,0.156124,0.355726,0.002251,0.027467,0.493798,0.496609,0,2007-09-07,1218,1
2,0.002253,0.002292,0.002225,0.002243,0.225996,0.003019,0.854950,0.844325,0.834970,0.831907,...,0.161973,0.356036,0.002207,0.073887,0.495221,0.498383,1,2007-09-10,1218,1
3,0.002245,0.002284,0.002218,0.002234,0.228876,0.003013,0.834789,0.848107,0.835675,0.852209,...,0.161973,0.356048,0.002168,0.112683,0.496594,0.500435,1,2007-09-11,1218,1
4,0.002240,0.002278,0.002212,0.002227,0.230907,0.003015,0.871258,0.863842,0.865963,0.865970,...,0.563712,0.356112,0.002133,0.148367,0.497138,0.501923,1,2007-09-12,1218,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888054,0.013860,0.013885,0.013982,0.013887,0.224440,0.011935,0.751128,0.742744,0.749802,0.747489,...,0.731551,0.354341,0.005365,0.395054,0.490866,0.493776,0,2015-12-24,9945,3
888055,0.013936,0.013965,0.014055,0.013961,0.217818,0.011993,0.733688,0.731544,0.733992,0.733117,...,0.736400,0.354158,0.005244,0.311885,0.490648,0.493084,1,2015-12-25,9945,3
888056,0.013999,0.014031,0.014117,0.014022,0.216852,0.012041,0.729041,0.725541,0.727577,0.723811,...,0.735977,0.354111,0.005147,0.244178,0.490608,0.492704,1,2015-12-28,9945,3
888057,0.014048,0.014081,0.014165,0.014070,0.220787,0.012079,0.730370,0.719938,0.723249,0.717575,...,0.735633,0.353953,0.005073,0.191684,0.490535,0.492452,1,2015-12-29,9945,3
888058,0.014089,0.014123,0.014207,0.014110,0.237793,0.012111,0.731472,0.730993,0.733259,0.733970,...,0.747922,0.353535,0.005022,0.150964,0.490406,0.492217,0,2015-12-30,9945,3

In [5]:
split_index = int(888059/2)

In [6]:
df_test1 = df_test.iloc[:split_index]

In [7]:
df_test2 = df_test.iloc[split_index:]

In [8]:
df_test1

,open_day1,high_day1,low_day1,close_day1,vol_day1,VWAP_day1,index_open_day1,index_high_day1,index_low_day1,index_close_day1,...,dealer_buy_kurtosis_day20,pvt_day20,ATR_day20,RSI_15_day20,SO5_day20,SO3_day20,Y,ts,StockNo,cluster
0,0.002263,0.002303,0.002237,0.002256,0.225242,0.003017,0.864141,0.856053,0.865558,0.860005,...,0.143095,0.355717,0.002299,0.027467,0.493005,0.495476,0,2007-09-06,1218,1
1,0.002259,0.002298,0.002232,0.002250,0.224382,0.003020,0.821859,0.825992,0.824660,0.822716,...,0.156124,0.355726,0.002251,0.027467,0.493798,0.496609,0,2007-09-07,1218,1
2,0.002253,0.002292,0.002225,0.002243,0.225996,0.003019,0.854950,0.844325,0.834970,0.831907,...,0.161973,0.356036,0.002207,0.073887,0.495221,0.498383,1,2007-09-10,1218,1
3,0.002245,0.002284,0.002218,0.002234,0.228876,0.003013,0.834789,0.848107,0.835675,0.852209,...,0.161973,0.356048,0.002168,0.112683,0.496594,0.500435,1,2007-09-11,1218,1
4,0.002240,0.002278,0.002212,0.002227,0.230907,0.003015,0.871258,0.863842,0.865963,0.865970,...,0.563712,0.356112,0.002133,0.148367,0.497138,0.501923,1,2007-09-12,1218,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444024,0.004831,0.004836,0.004867,0.004833,0.220597,0.014529,0.644716,0.638706,0.638129,0.639566,...,0.169163,0.356184,0.002220,0.089046,0.499941,0.505418,0,2012-05-09,2542,3
444025,0.004796,0.004800,0.004831,0.004797,0.221921,0.014429,0.637817,0.630206,0.633222,0.630515,...,0.204824,0.356279,0.002210,0.168801,0.501786,0.508361,0,2012-05-10,2542,3
444026,0.004762,0.004765,0.004796,0.004762,0.220310,0.014325,0.626524,0.619133,0.622144,0.620976,...,0.204094,0.356191,0.002200,0.182378,0.502030,0.510040,0,2012-05-11,2542,3
444027,0.004723,0.004725,0.004756,0.004723,0.219521,0.014211,0.613681,0.607359,0.610115,0.608323,...,0.199707,0.355925,0.002190,0.167941,0.499765,0.508956,0,2012-05-14,2542,3
444028,0.004681,0.004683,0.004713,0.004681,0.217897,0.014088,0.599297,0.594827,0.597084,0.593141,...,0.224613,0.355724,0.002180,0.149641,0.497204,0.506240,0,2012-05-15,2542,3

In [9]:
df_test2

,open_day1,high_day1,low_day1,close_day1,vol_day1,VWAP_day1,index_open_day1,index_high_day1,index_low_day1,index_close_day1,...,dealer_buy_kurtosis_day20,pvt_day20,ATR_day20,RSI_15_day20,SO5_day20,SO3_day20,Y,ts,StockNo,cluster
444029,0.004646,0.004648,0.004678,0.004646,0.216993,0.013988,0.594859,0.588458,0.591622,0.590835,...,0.265597,0.355570,0.002170,0.124689,0.495894,0.503770,0,2012-05-16,2542,3
444030,0.004620,0.004621,0.004651,0.004620,0.216770,0.013913,0.601550,0.589199,0.594814,0.595885,...,0.264032,0.355462,0.002160,0.104571,0.494791,0.501598,0,2012-05-17,2542,3
444031,0.004598,0.004598,0.004629,0.004598,0.221043,0.013849,0.613546,0.608647,0.613983,0.614180,...,0.154256,0.355484,0.002149,0.088591,0.494306,0.500100,0,2012-05-18,2542,3
444032,0.004583,0.004583,0.004613,0.004582,0.219267,0.013806,0.617697,0.604627,0.605518,0.600945,...,0.164929,0.355435,0.002138,0.071605,0.493709,0.498845,0,2012-05-21,2542,3
444033,0.004567,0.004567,0.004597,0.004567,0.220036,0.013763,0.620788,0.608590,0.608484,0.600128,...,0.130663,0.355325,0.002127,0.056603,0.493251,0.497828,0,2012-05-22,2542,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888054,0.013860,0.013885,0.013982,0.013887,0.224440,0.011935,0.751128,0.742744,0.749802,0.747489,...,0.731551,0.354341,0.005365,0.395054,0.490866,0.493776,0,2015-12-24,9945,3
888055,0.013936,0.013965,0.014055,0.013961,0.217818,0.011993,0.733688,0.731544,0.733992,0.733117,...,0.736400,0.354158,0.005244,0.311885,0.490648,0.493084,1,2015-12-25,9945,3
888056,0.013999,0.014031,0.014117,0.014022,0.216852,0.012041,0.729041,0.725541,0.727577,0.723811,...,0.735977,0.354111,0.005147,0.244178,0.490608,0.492704,1,2015-12-28,9945,3
888057,0.014048,0.014081,0.014165,0.014070,0.220787,0.012079,0.730370,0.719938,0.723249,0.717575,...,0.735633,0.353953,0.005073,0.191684,0.490535,0.492452,1,2015-12-29,9945,3
888058,0.014089,0.014123,0.014207,0.014110,0.237793,0.012111,0.731472,0.730993,0.733259,0.733970,...,0.747922,0.353535,0.005022,0.150964,0.490406,0.492217,0,2015-12-30,9945,3

In [10]:
df_test1.to_csv(r'D:\OneDrive - SinoPac\training\train_large_1.csv', index=False)

In [11]:
df_test2.to_csv(r'D:\OneDrive - SinoPac\training\train_large_2.csv', index=False)

In [ ]:
df_test.isnull().values.any()

In [ ]:
df_test.describe()

In [8]:
df_test1 = pd.read_csv(r'D:\OneDrive - SinoPac\training\train_large.csv')

In [10]:
df_test2 = pd.read_csv(r'D:\OneDrive - SinoPac\training\val_large.csv')

In [11]:
df_complete = pd.concat([df_test1,df_test2])

In [18]:
df_complete

,open_day1,high_day1,low_day1,close_day1,vol_day1,VWAP_day1,index_open_day1,index_high_day1,index_low_day1,index_close_day1,...,dealer_buy_kurtosis_day20,pvt_day20,ATR_day20,RSI_15_day20,SO5_day20,SO3_day20,Y,ts,StockNo,cluster
0,0.002263,0.002303,0.002237,0.002256,0.225242,0.003017,0.864141,0.856053,0.865558,0.860005,...,0.143095,0.355717,0.002299,0.027467,0.493005,0.495476,0,2007-09-06,1218,1
1,0.002259,0.002298,0.002232,0.002250,0.224382,0.003020,0.821859,0.825992,0.824660,0.822716,...,0.156124,0.355726,0.002251,0.027467,0.493798,0.496609,0,2007-09-07,1218,1
2,0.002253,0.002292,0.002225,0.002243,0.225996,0.003019,0.854950,0.844325,0.834970,0.831907,...,0.161973,0.356036,0.002207,0.073887,0.495221,0.498383,1,2007-09-10,1218,1
3,0.002245,0.002284,0.002218,0.002234,0.228876,0.003013,0.834789,0.848107,0.835675,0.852209,...,0.161973,0.356048,0.002168,0.112683,0.496594,0.500435,1,2007-09-11,1218,1
4,0.002240,0.002278,0.002212,0.002227,0.230907,0.003015,0.871258,0.863842,0.865963,0.865970,...,0.563712,0.356112,0.002133,0.148367,0.497138,0.501923,1,2007-09-12,1218,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196140,0.010532,0.010478,0.010666,0.010543,0.221141,0.009114,1.085322,1.081665,1.091045,1.087228,...,0.564662,0.356554,0.002645,0.659460,0.505172,0.514478,1,2017-08-24,9945,3
196141,0.010523,0.010468,0.010657,0.010534,0.220598,0.009103,1.082659,1.080653,1.087066,1.087647,...,0.571674,0.356651,0.002699,0.730819,0.506502,0.516895,1,2017-08-25,9945,3
196142,0.010514,0.010460,0.010648,0.010525,0.220610,0.009093,1.085993,1.082591,1.093648,1.088703,...,0.533162,0.356762,0.002761,0.785587,0.507693,0.519114,1,2017-08-28,9945,3
196143,0.010506,0.010452,0.010640,0.010517,0.220292,0.009083,1.080872,1.080214,1.086441,1.079510,...,0.402298,0.357081,0.002831,0.829245,0.508777,0.521144,1,2017-08-29,9945,3
196144,0.010498,0.010444,0.010632,0.010509,0.219689,0.009074,1.081076,1.081156,1.086977,1.094469,...,0.417043,0.357493,0.002907,0.863347,0.509753,0.522988,1,2017-08-30,9945,3

In [21]:
df_complete.to_csv(r'D:\OneDrive - SinoPac\training\large_train_val.csv', index=False)

In [23]:
prob_list = []
for i in range (len(df_test1.columns)):
    if '%' in df_test1.columns[i]:
        prob_list.append(df_test1.columns[i])

In [24]:
fixed_list = [p.replace('%','') for p in prob_list]

In [25]:
fixed_dict = dict(zip(prob_list,fixed_list))

In [26]:
fixed_dict

{'SO%k5_day1': 'SOk5_day1',
 'SO%d3_day1': 'SOd3_day1',
 'SO%k5_day2': 'SOk5_day2',
 'SO%d3_day2': 'SOd3_day2',
 'SO%k5_day3': 'SOk5_day3',
 'SO%d3_day3': 'SOd3_day3',
 'SO%k5_day4': 'SOk5_day4',
 'SO%d3_day4': 'SOd3_day4',
 'SO%k5_day5': 'SOk5_day5',
 'SO%d3_day5': 'SOd3_day5',
 'SO%k5_day6': 'SOk5_day6',
 'SO%d3_day6': 'SOd3_day6',
 'SO%k5_day7': 'SOk5_day7',
 'SO%d3_day7': 'SOd3_day7',
 'SO%k5_day8': 'SOk5_day8',
 'SO%d3_day8': 'SOd3_day8',
 'SO%k5_day9': 'SOk5_day9',
 'SO%d3_day9': 'SOd3_day9',
 'SO%k5_day10': 'SOk5_day10',
 'SO%d3_day10': 'SOd3_day10',
 'SO%k5_day11': 'SOk5_day11',
 'SO%d3_day11': 'SOd3_day11',
 'SO%k5_day12': 'SOk5_day12',
 'SO%d3_day12': 'SOd3_day12',
 'SO%k5_day13': 'SOk5_day13',
 'SO%d3_day13': 'SOd3_day13',
 'SO%k5_day14': 'SOk5_day14',
 'SO%d3_day14': 'SOd3_day14',
 'SO%k5_day15': 'SOk5_day15',
 'SO%d3_day15': 'SOd3_day15',
 'SO%k5_day16': 'SOk5_day16',
 'SO%d3_day16': 'SOd3_day16',
 'SO%k5_day17': 'SOk5_day17',
 'SO%d3_day17': 'SOd3_day17',
 'SO%k5_day18': 'SOk5_day18',
 'SO%d3_day18': 'SOd3_day18',
 'SO%k5_day19': 'SOk5_day19',
 'SO%d3_day19': 'SOd3_day19',
 'SO%k5_day20': 'SOk5_day20',
 'SO%d3_day20': 'SOd3_day20'}

In [27]:
df_test1 = df_test1.rename(columns=fixed_dict)

In [28]:
df_test1.to_csv('high_val_cluster_complete_2.csv', index=False)

In [29]:
df_test1.describe()

,close_day1,high_day1,low_day1,open_day1,vol_day1,VWAP_day1,ma7_day1,ma21_day1,26ema_day1,12ema_day1,...,dealer_buy_day20,foreign_buy_skew_day20,foreign_buy_kurtosis_day20,investment_buy_skew_day20,investment_buy_kurtosis_day20,dealer_buy_skew_day20,dealer_buy_kurtosis_day20,Y,StockNo,cluster
count,812461.000000,812461.000000,812461.000000,812461.000000,812461.000000,812461.000000,812461.000000,812461.000000,812461.000000,812461.000000,...,812461.000000,812461.000000,812461.000000,8.124610e+05,812461.000000,812461.000000,812461.000000,812461.000000,812461.000000,812461.000000
mean,0.092866,0.092511,0.093052,0.093204,0.107898,0.095987,0.093779,0.093310,0.093913,0.093669,...,0.497758,0.502835,0.279277,4.799092e-01,0.350883,0.502041,0.386235,0.478222,3843.807351,2.657874
std,0.105522,0.105294,0.105374,0.105754,0.030911,0.105530,0.106725,0.106738,0.107338,0.106785,...,0.129325,0.167112,0.182543,2.607620e-01,0.353435,0.218300,0.234461,0.499526,2193.509105,1.193930
min,0.000000,0.000000,0.000000,0.000000,-0.125823,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.098462,0.000000,0.000000,-3.226233e-16,0.000000,0.000000,0.000000,0.000000,1101.000000,0.000000
25%,0.032649,0.032454,0.032802,0.032787,0.094607,0.035938,0.032908,0.032483,0.032685,0.032730,...,0.390900,0.408860,0.160063,3.181639e-01,0.000000,0.375989,0.216856,0.000000,2388.000000,2.000000
50%,0.059825,0.059538,0.060084,0.060076,0.107464,0.063252,0.060390,0.059796,0.060189,0.060177,...,0.469585,0.501184,0.221636,5.000000e-01,0.264984,0.500237,0.326840,0.000000,3014.000000,3.000000
75%,0.110224,0.109892,0.110439,0.110669,0.118476,0.113710,0.111164,0.110437,0.111148,0.110925,...,0.611677,0.598422,0.337001,5.923949e-01,0.573810,0.633600,0.508226,1.000000,4976.000000,4.000000
max,1.735590,1.714609,1.726560,1.723188,1.031159,1.723348,1.754488,1.735703,1.722641,1.741549,...,1.173831,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,9958.000000,4.000000