In [1]:
import numpy as np 
import pandas as pd 
import datetime
from datetime import datetime, date
from tqdm import tqdm_notebook as tqdm
import time

from multiprocessing import Pool
from functools import partial
import VWAP_feature_function as func

In [2]:
data = pd.read_csv('D:\\庫存健診開發\\data\\processed\\TWSE_stock_processed_unfixed.csv', converters={'ts': str, 'StockName': str, 'StockNo': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,ts,StockNo,StockName,open,high,low,close,return,volatility,vol,...,index_vol,industry_open,industry_high,industry_low,industry_close,industry_return,industry_vol,foreign_buy,investment_buy,dealer_buy
0,2007-07-02,1102,亞泥,43.45,43.70,42.95,43.7,0.92,1.73,5031.0,...,5490199.0,125.08,125.09,122.87,124.56,0.02,44467.0,1476.0,-75.0,-27.0
1,2007-07-03,1102,亞泥,43.40,43.95,43.35,43.5,-0.46,1.37,5145.0,...,6604477.0,124.69,125.49,123.77,124.54,-0.02,76827.0,-629.0,579.0,-27.0
2,2007-07-04,1102,亞泥,43.50,44.50,43.50,43.8,0.69,2.30,5166.0,...,7261940.0,124.83,127.13,124.56,125.13,0.47,48887.0,-325.0,312.0,66.0
3,2007-07-05,1102,亞泥,43.85,43.85,42.60,42.9,-2.05,2.85,11406.0,...,7065444.0,125.46,125.46,122.82,123.23,-1.52,55899.0,-6742.0,524.0,1003.0
4,2007-07-06,1102,亞泥,42.00,42.90,41.90,42.3,-1.40,2.33,17719.0,...,7514284.0,122.77,125.91,121.95,125.67,1.98,103863.0,-10364.0,109.0,-20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369242,2019-09-17,9958,世紀鋼,78.90,78.90,77.10,77.3,-0.26,2.32,3050.0,...,4238581.0,102.59,102.71,101.54,101.55,-1.14,31349.0,508.0,0.0,-358.0
2369243,2019-09-18,9958,世紀鋼,77.90,79.30,77.50,77.7,0.91,2.34,5940.0,...,4380466.0,101.42,102.19,101.42,101.80,0.25,33530.0,-291.0,0.0,144.0
2369244,2019-09-19,9958,世紀鋼,78.40,78.40,76.20,76.3,-1.80,2.83,4011.0,...,4094710.0,101.80,102.03,101.31,101.59,-0.21,22747.0,64.0,0.0,-161.0
2369245,2019-09-20,9958,世紀鋼,76.60,77.00,75.80,75.8,-0.66,1.57,1742.0,...,4712806.0,101.46,102.10,101.33,102.10,0.50,55930.0,144.0,0.0,21.0
2369246,2019-09-23,9958,世紀鋼,75.80,76.50,75.40,75.8,0.00,1.45,1530.0,...,3976566.0,101.45,101.76,101.18,101.19,-0.89,27986.0,110.0,0.0,-114.0

In [3]:
columns_dict = {'lag': ['index_close', 'industry_close', 'close', 'VWAP'],
               'return': ['index', 'industry', 'close', 'VWAP'],
               'ratio': ['index_close', 'index_vol', 'index_return', 'industry_close', 'industry_vol', 'industry_return', 'index_close_slope', 'index_VWAP_slope', 'industry_close_slope', 'industry_VWAP_slope', 'VWAP_return', 'return', 'vol', 'VWAP'],
               'momentum': ['index_close', 'index_vol', 'index_return', 'industry_close', 'industry_vol', 'industry_return', 'index_close_slope', 'index_VWAP_slope', 'industry_close_slope', 'industry_VWAP_slope', 'VWAP_return', 'return', 'vol', 'VWAP'],
                'moment': ['index_close', 'index_vol', 'industry_close', 'industry_vol', 'vol', 'VWAP'],
                'buyer': ['foreign_buy', 'investment_buy', 'dealer_buy']
               }

In [4]:
df_list = [group[1] for group in data.groupby(data['StockNo'])]
output_list = []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_engineering, columns_dict=columns_dict), df_list), total=len(df_list)), 1):
            output_list.append(x)
                
df = pd.concat(output_list, axis=0)
df

HBox(children=(IntProgress(value=0, max=935), HTML(value='')))

,ts,StockNo,StockName,open,high,low,close,return,volatility,vol,...,ATR,index_pvt,industry_pvt,foreign_pvt,investment_pvt,dealer_pvt,pvt,RSI_15,SOk5,SOd3
0,2007-07-02,1109,信大,12.9,13.25,12.80,13.25,3.52,3.52,3973.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
1,2007-07-03,1109,信大,13.3,13.80,13.30,13.50,1.89,3.77,11494.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
2,2007-07-04,1109,信大,13.5,13.70,13.30,13.45,-0.37,2.96,2437.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
3,2007-07-05,1109,信大,13.5,13.60,13.30,13.30,-1.12,2.23,1754.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
4,2007-07-06,1109,信大,13.4,13.65,13.00,13.55,1.88,4.89,2388.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.584841,0.301853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2878,2019-09-16,9955,佳龍,19.6,19.70,19.45,19.50,1.04,1.30,1116.0,...,0.647764,217140.288663,353.570291,-16.429651,2.026157e-14,0.024804,92.715031,0.405340,0.431838,0.283033
2879,2019-09-17,9955,佳龍,19.5,19.60,19.30,19.30,-1.03,1.54,544.0,...,0.604293,178164.088200,256.276603,-13.294386,2.026157e-14,0.024804,186.917853,0.381846,0.344275,0.313654
2880,2019-09-18,9955,佳龍,19.3,19.35,19.15,19.15,-0.78,1.04,442.0,...,0.564005,185681.972022,469.288133,-12.803724,2.026157e-14,0.024804,172.887368,0.358123,0.348133,0.330894
2881,2019-09-19,9955,佳龍,19.1,19.10,18.65,18.80,-1.83,2.35,957.0,...,0.565818,171429.641857,254.418675,-12.126317,2.026157e-14,0.024804,151.287775,0.289586,0.154202,0.242548
2882,2019-09-20,9955,佳龍,18.8,19.20,18.80,19.15,1.86,2.13,538.0,...,0.545090,184903.237186,117.269799,-9.378818,2.026157e-14,0.024804,176.540236,0.319360,0.436006,0.339277

In [5]:
d = df[df['MACD_diff'].notnull()]
d = d[d['Y'].notnull()]
d = d.fillna(0)

In [11]:
d.to_csv('D:\\庫存健診開發\\data\\processed\\TWSE_feature_all_new.csv', index=False)

In [8]:
'industry_return' in df.columns

True

In [10]:
'average_volatility' in df.columns

False