In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import datetime, timedelta, date
from tqdm import tqdm_notebook as tqdm

from multiprocessing import Pool
from functools import partial
import Training_function as func

In [2]:
data = pd.read_csv('D:\\庫存健診開發\\data\\Stock\\TWSE_Stock_feature.csv', converters={'ts': str, 'StockNo': str, 'StockName': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,lower_band,skew,kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
0,嘉泥,1103,21.296674,21.865448,20.975740,21.462088,NaN,333925503.0,2004-02-11,1.540757e+07,...,NaN,NaN,NaN,NaN,NaN,0.889707,0.889707,0.000000,0.000000,0.000000
1,嘉泥,1103,21.293410,21.856344,20.975407,21.458549,-0.9,246048766.0,2004-02-12,1.261464e+07,...,NaN,NaN,NaN,-1933.246953,NaN,0.880937,0.885030,0.000000,0.000000,0.000000
2,嘉泥,1103,21.290035,21.846936,20.975061,21.454905,0.4,333309529.0,2004-02-13,1.389159e+07,...,NaN,NaN,NaN,-2202.180939,-4135.427892,0.871875,0.880048,0.000000,0.000000,0.000000
3,嘉泥,1103,21.286540,21.837203,20.974701,21.451152,1.0,515700813.0,2004-02-16,1.544741e+07,...,NaN,NaN,NaN,-2535.341304,-4737.522243,0.862502,0.874748,0.000000,0.000000,0.000000
4,嘉泥,1103,21.282995,21.827354,20.974325,21.447354,-0.1,333141524.0,2004-02-17,1.429967e+07,...,NaN,NaN,NaN,-2381.590908,-4916.932212,0.853029,0.869174,0.000000,0.346383,0.178778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870369,世紀鋼,9958,76.348356,77.628386,75.866043,76.750901,-0.2,237190800.0,2019-09-17,4.322005e+06,...,67.794944,0.157269,-1.657966,-6917.656338,1074.106071,1.762344,2.053091,0.823950,0.379665,0.474749
2870370,世紀鋼,9958,76.066016,77.361494,75.746432,76.633749,0.4,464879118.0,2019-09-18,3.066161e+06,...,67.818320,-0.009699,-1.739897,-11338.824364,-18256.480703,1.615062,1.998337,0.789301,0.253416,0.364083
2870371,世紀鋼,9958,75.951315,77.251652,75.744959,76.626244,-1.4,308696223.0,2019-09-19,2.464138e+06,...,67.956700,-0.197361,-1.723848,-3715.723244,-15054.547608,1.506693,1.936882,0.788834,0.162948,0.263515
2870372,世紀鋼,9958,75.986793,77.281113,75.838004,76.705426,-0.5,132881305.0,2019-09-20,2.295856e+06,...,68.197528,-0.399103,-1.605250,1072.435713,-2643.287531,1.443109,1.875160,0.791651,0.121482,0.192499
2870373,世紀鋼,9958,76.075653,77.355967,75.965079,76.812014,0.0,116145620.0,2019-09-23,2.735556e+06,...,68.567940,-0.618851,-1.356955,3198.991040,4271.426753,1.390888,1.814626,0.799421,0.175581,0.184040

In [3]:
train_df = pd.read_csv('D:\\庫存健診開發\\data\\Clustering\\train_cluster.csv', index_col=0)
test_df = pd.read_csv('D:\\庫存健診開發\\data\\Clustering\\test_cluster.csv', index_col=0)

In [4]:
file_path = 'D:\\庫存健診開發\\data\\Training\\Raw\\'
func.ClusterSplit(train_df, test_df, data, file_path)

HBox(children=(IntProgress(value=0, max=9), HTML(value='')))

In [2]:
data = pd.read_csv('D:\\庫存健診開發\\data\\Training\\Raw\\Cluster_0.csv', converters={'ts': str, 'StockNo': str, 'StockName': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,lower_band,skew,kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
0,亞泥,1102,23.869740,24.366515,23.277261,23.766541,NaN,1.895267e+08,2004-02-11,1.953132e+07,...,NaN,NaN,NaN,NaN,NaN,1.089254,1.089254,0.000000,0.000000,0.000000
1,亞泥,1102,23.900024,24.396603,23.318646,23.805446,-0.5,2.468034e+08,2004-02-12,9.896328e+06,...,NaN,NaN,NaN,12555.716747,NaN,1.077957,1.083229,0.000000,0.000000,0.000000
2,亞泥,1102,23.931360,24.427742,23.361480,23.845723,1.4,8.446286e+08,2004-02-13,2.937028e+07,...,NaN,NaN,NaN,38508.350723,51064.067470,1.066261,1.076803,0.000000,0.000000,0.000000
3,亞泥,1102,23.963821,24.460004,23.405864,23.887465,0.4,1.132873e+09,2004-02-16,3.486248e+07,...,NaN,NaN,NaN,47288.042327,85796.393050,1.054141,1.069958,0.000000,0.000000,0.000000
4,亞泥,1102,23.996646,24.492628,23.450749,23.929679,0.8,6.549583e+08,2004-02-17,3.180797e+07,...,NaN,NaN,NaN,43568.844907,90856.887234,1.041878,1.062752,0.000000,0.591908,0.305501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262674,豐泰,9910,212.664249,215.452195,211.104309,212.621361,1.5,1.365693e+08,2019-09-17,1.587933e+06,...,194.231677,0.527215,-1.144179,-4922.734473,-5698.862772,4.347886,4.092430,0.843744,0.559036,0.653585
262675,豐泰,9910,211.094301,213.994288,210.085503,211.051012,-2.0,4.263209e+08,2019-09-18,1.009538e+06,...,194.420223,0.314253,-1.366811,-7452.694728,-12375.429201,3.908786,4.069474,0.743342,0.171682,0.412633
262676,豐泰,9910,210.585291,213.624853,209.860156,210.550065,-0.5,1.918511e+08,2019-09-19,9.299355e+05,...,194.822773,0.113646,-1.459570,-2242.348658,-9695.043386,3.764697,4.031377,0.721635,0.118849,0.265741
262677,豐泰,9910,211.293958,214.514407,210.545322,211.305370,-1.0,4.088073e+08,2019-09-20,1.411221e+06,...,195.129915,-0.065605,-1.522651,4749.081522,2506.732864,3.969084,4.023591,0.754038,0.234999,0.250370
262678,豐泰,9910,211.967225,215.326795,211.180972,211.998248,0.5,1.974065e+08,2019-09-23,1.371041e+06,...,195.457910,-0.256997,-1.485471,4368.680040,9117.761562,4.145823,4.038870,0.780684,0.376798,0.313584

In [3]:
train_df, val_df, test_df = func.TrainTestSplit(data, date(2016,1,1), date(2017,9,1))

D:\庫存健診開發\code\TrainingPrep\Training_function.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  train_df = data[data['ts'].dt.date < TrainDate][data['26ema'].notnull()]
D:\庫存健診開發\code\TrainingPrep\Training_function.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  val_df = data[data['ts'].dt.date < valDate][data['ts'].dt.date >= TrainDate][data['26ema'].notnull()]
D:\庫存健診開發\code\TrainingPrep\Training_function.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  test_df = data[data['ts'].dt.date >= valDate][data['26ema'].notnull()]

In [5]:
feature_list = ['close', 'high', 'low', 'open',
       'vol', 'VWAP', 'ma7', 'ma21', '26ema', '12ema', 'MACD', 'upper_band',
       'lower_band', 'skew', 'kurtosis', 'pvt', 'ATR',
       'RSI_15', 'SO%k5', 'SO%d3']

print(train_df[feature_list].isna().values.any())
print(val_df[feature_list].isna().values.any())
print(test_df[feature_list].isna().values.any())

False
False
False

In [6]:
param = func.GetScalerParam(train_df, feature_list)
param

                     max           min           std          mean
close       3.424696e+03  1.590563e+00  1.582414e+02  7.681878e+01
high        3.494900e+03  1.615001e+00  1.610329e+02  7.793082e+01
low         3.401917e+03  1.562440e+00  1.559097e+02  7.583367e+01
open        3.460131e+03  1.583817e+00  1.585801e+02  7.692518e+01
vol         1.718654e+09 -2.427316e+08  1.957121e+07  1.479351e+07
VWAP        3.443728e+03  0.000000e+00  1.584522e+02  7.686671e+01
ma7         3.365565e+03  1.591341e+00  1.580063e+02  7.677509e+01
ma21        3.354778e+03  1.596543e+00  1.573929e+02  7.666420e+01
26ema       3.335788e+03  1.614660e+00  1.569624e+02  7.661492e+01
12ema       3.361095e+03  1.596358e+00  1.577393e+02  7.673472e+01
MACD        1.257517e+02 -1.498371e+02  4.525148e+00  1.197938e-01
upper_band  3.500378e+03  1.606311e+00  1.678502e+02  8.022897e+01
lower_band  3.287166e+03 -6.546928e+01  1.471984e+02  7.309943e+01
skew        4.129428e+00 -4.113119e+00  6.040371e-01 -1.317327e-02
kurtosis    1.505234e+01 -1.998610e+00  7.524385e-01 -8.414516e-01
pvt         2.386969e+07 -6.238902e+06  2.863910e+05  6.699577e+03
ATR         1.809449e+02  5.282830e-02  5.781457e+00  2.170859e+00
RSI_15      1.000000e+00  0.000000e+00  4.116801e-01  5.205103e-01
SO%k5       1.509499e+00 -3.124738e-01  1.840484e-01  4.878565e-01
SO%d3       1.211839e+00 -6.731475e-02  1.763369e-01  4.878641e-01

In [7]:
train_df, val_df, test_df = func.Scaler(train_df, feature_list, param), func.Scaler(val_df, feature_list, param), func.Scaler(test_df, feature_list, param)
display(train_df)
display(test_df)

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,lower_band,skew,kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
24,亞泥,1102,0.006404,0.006406,0.006334,0.006349,-0.30,310866303.0,2004-03-16,0.133052,...,0.026550,0.394791,0.083439,-47902.399949,0.204056,0.895503,0.004854,0.045649,0.371058,0.341643
25,亞泥,1102,0.006385,0.006388,0.006316,0.006331,-1.30,346863303.0,2004-03-17,0.127142,...,0.026528,0.407277,0.073030,-18024.293974,0.205024,0.890688,0.004826,0.037261,0.368976,0.337770
26,亞泥,1102,0.006366,0.006368,0.006297,0.006313,0.80,289156687.0,2004-03-18,0.129164,...,0.026506,0.417999,0.065862,-30615.535921,0.205598,0.886101,0.004797,0.030431,0.366378,0.333983
27,亞泥,1102,0.006345,0.006348,0.006277,0.006293,-0.40,143443290.0,2004-03-19,0.130670,...,0.026482,0.426842,0.061068,-41708.513761,0.204811,0.881781,0.004770,0.024857,0.363099,0.329755
28,亞泥,1102,0.006323,0.006326,0.006257,0.006273,-1.70,5433306.0,2004-03-22,0.130375,...,0.026458,0.434230,0.057606,-41133.705304,0.204462,0.877431,0.004743,0.020461,0.360048,0.325467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229900,潤泰新,9945,0.011645,0.011583,0.011647,0.011603,0.20,61302162.0,2015-12-25,0.124882,...,0.031929,0.403685,0.087370,-10154.395200,0.206389,0.909170,0.004582,0.063797,0.260608,0.182050
229901,潤泰新,9945,0.011607,0.011547,0.011609,0.011568,-0.30,79530579.0,2015-12-28,0.124933,...,0.031863,0.408927,0.071875,-7170.656124,0.206638,0.913768,0.004604,0.057148,0.264367,0.183473
229902,潤泰新,9945,0.011579,0.011520,0.011580,0.011541,0.15,66482457.0,2015-12-29,0.124992,...,0.031801,0.420441,0.055671,-5621.219582,0.206788,0.918368,0.004627,0.052435,0.272674,0.190101
229903,潤泰新,9945,0.011567,0.011508,0.011567,0.011529,-0.50,110964914.0,2015-12-30,0.125126,...,0.031745,0.437578,0.041075,-2667.593924,0.206938,0.922606,0.004649,0.050286,0.288881,0.204956
229904,潤泰新,9945,0.011555,0.011496,0.011554,0.011517,-0.40,122208750.0,2015-12-31,0.125310,...,0.031695,0.456593,0.030379,-3067.158340,0.207023,0.926409,0.004672,0.048007,0.304068,0.223200

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,lower_band,skew,kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
230311,亞泥,1102,0.007530,0.007403,0.007535,0.007451,0.10,94790172.0,2017-09-01,0.125536,...,0.027315,0.930446,0.827289,100131.207017,0.210688,0.873443,0.001712,0.968014,0.668619,0.734614
230312,亞泥,1102,0.007525,0.007397,0.007529,0.007444,0.00,46852247.0,2017-09-04,0.124695,...,0.027287,0.794944,0.375853,-1123.134367,0.210502,0.289917,0.001662,0.944271,0.660374,0.741783
230313,亞泥,1102,0.007520,0.007391,0.007523,0.007438,0.00,100375245.0,2017-09-05,0.125640,...,0.027273,0.721068,0.210036,-2153.200537,0.207104,0.288386,0.001617,0.918182,0.651841,0.739290
230314,亞泥,1102,0.007516,0.007384,0.007517,0.007431,-0.25,88723794.0,2017-09-06,0.125280,...,0.027267,0.670791,0.125799,-1614.047005,0.207088,0.287165,0.001577,0.890237,0.643318,0.731974
230315,亞泥,1102,0.007510,0.007376,0.007509,0.007422,-0.10,73188947.0,2017-09-07,0.125237,...,0.027267,0.632440,0.076370,-2318.861314,0.207083,0.285138,0.001540,0.849463,0.461555,0.598868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262674,豐泰,9910,0.061661,0.061214,0.061624,0.061019,1.50,136569295.0,2019-09-17,0.124565,...,0.077462,0.562973,0.050110,-4922.734473,0.207024,4.347886,0.022332,0.843744,0.478333,0.563575
262675,豐泰,9910,0.061203,0.060796,0.061324,0.060565,-2.00,426320900.0,2019-09-18,0.124270,...,0.077518,0.537136,0.037054,-7452.694728,0.206802,3.908786,0.022205,0.743342,0.265732,0.375207
262676,豐泰,9910,0.061054,0.060691,0.061258,0.060420,-0.50,191851142.0,2019-09-19,0.124229,...,0.077638,0.512798,0.031614,-2242.348658,0.206891,3.764697,0.021994,0.721635,0.236734,0.260372
262677,豐泰,9910,0.061261,0.060945,0.061459,0.060639,-1.00,408807276.0,2019-09-20,0.124475,...,0.077730,0.491051,0.027914,4749.081522,0.207297,3.969084,0.021951,0.754038,0.300483,0.248355
262678,豐泰,9910,0.061458,0.061178,0.061646,0.060839,0.50,197406460.0,2019-09-23,0.124454,...,0.077827,0.467831,0.030094,4368.680040,0.207516,4.145823,0.022035,0.780684,0.378311,0.297774

In [8]:
df_list = [group[1] for group in train_df.groupby(train_df['StockNo'])]

X_train, Y_train = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_elimination, lookback=20, forward=5, feature_list=feature_list), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_train.append(xx.tolist())
            Y_train.extend(x[1])

np.array(X_train).shape

HBox(children=(IntProgress(value=0, max=72), HTML(value='')))

(197067, 20, 20)

In [9]:
df_list = [group[1] for group in val_df.groupby(val_df['StockNo'])]

X_val, Y_val = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_elimination, lookback=20, forward=5, feature_list=feature_list), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_val.append(xx.tolist())
            Y_val.extend(x[1])

np.array(X_val).shape

HBox(children=(IntProgress(value=0, max=73), HTML(value='')))

(27592, 20, 20)

In [10]:
df_list = [group[1] for group in test_df.groupby(test_df['StockNo'])]

X_test, Y_test = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.create_dataset, lookback=20, forward=5, feature_list=feature_list, problem='classification'), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_test.append(xx.tolist())
            Y_test.extend(x[1])

np.array(X_test).shape

HBox(children=(IntProgress(value=0, max=65), HTML(value='')))

(30695, 20, 20)

In [11]:
(len(X_train) == len(Y_train)) and (len(X_val) == len(Y_val)) and (len(X_test) == len(Y_test))

True

In [12]:
save_list = [X_train, Y_train, X_val, Y_val, X_test, Y_test]

In [13]:
cluster = 0
import pickle
with open(f'D:\\庫存健診開發\\data\\Training\\processed\\Cluster_{cluster}_classification_minmax0_Weekly', 'wb') as fp:
    pickle.dump(save_list, fp)