In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import datetime, timedelta, date
from tqdm import tqdm_notebook as tqdm
import seaborn as sns

from multiprocessing import Pool
from functools import partial
import Training_function as func

In [2]:
data = pd.read_csv('D:\\庫存健診開發\\data\\Stock\\TWSE_Stock_feature.csv', converters={'ts': str, 'StockNo': str, 'StockName': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,investment_buy_kurtosis,dealer_buy_skew,dealer_buy_kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
0,亞泥,1102,23.869740,24.366515,23.277261,23.766541,NaN,1.895267e+08,2004-02-11,1.953132e+07,...,NaN,NaN,NaN,NaN,NaN,1.089254,1.089254,0.000000,0.000000,0.000000
1,亞泥,1102,23.900024,24.396603,23.318646,23.805446,-0.50,2.468034e+08,2004-02-12,9.896328e+06,...,NaN,NaN,NaN,12555.716747,NaN,1.077957,1.083229,0.000000,0.000000,0.000000
2,亞泥,1102,23.931360,24.427742,23.361480,23.845723,1.40,8.446286e+08,2004-02-13,2.937028e+07,...,NaN,NaN,NaN,38508.350723,51064.067470,1.066261,1.076803,0.000000,0.000000,0.000000
3,亞泥,1102,23.963821,24.460004,23.405864,23.887465,0.40,1.132873e+09,2004-02-16,3.486248e+07,...,NaN,NaN,NaN,47288.042327,85796.393050,1.054141,1.069958,0.000000,0.000000,0.000000
4,亞泥,1102,23.996646,24.492628,23.450749,23.929679,0.80,6.549583e+08,2004-02-17,3.180797e+07,...,NaN,NaN,NaN,43568.844907,90856.887234,1.041878,1.062752,0.000000,0.591908,0.305501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870369,潤泰新,9945,42.597097,42.882676,42.478737,42.769965,0.00,4.273570e+07,2019-09-17,9.913275e+05,...,14.891503,0.774622,-0.069637,-2939.578552,-5810.041361,0.403939,0.446959,0.394791,0.173960,0.230880
2870370,潤泰新,9945,42.508437,42.815835,42.407700,42.711107,-0.30,6.837791e+07,2019-09-18,1.560745e+06,...,14.379924,0.959324,0.222628,-3248.485107,-6188.063659,0.408136,0.442106,0.347899,0.146203,0.188541
2870371,潤泰新,9945,42.456466,42.772982,42.365112,42.673485,-0.55,5.453982e+07,2019-09-19,1.289888e+06,...,14.379924,0.959324,0.222628,-1577.016568,-4825.501675,0.407870,0.437827,0.321718,0.133362,0.160952
2870372,潤泰新,9945,42.423662,42.743618,42.336151,42.646875,-0.50,1.163660e+08,2019-09-20,2.742475e+06,...,7.977569,0.946702,0.183959,-2119.021081,-3696.037649,0.407467,0.434032,0.303942,0.137104,0.149028
2870373,潤泰新,9945,42.425955,42.738238,42.333337,42.641086,-0.15,7.036625e+07,2019-09-23,1.604318e+06,...,13.563851,1.080792,0.370129,86.744902,-2032.276179,0.404901,0.430391,0.302088,0.168600,0.158814

In [2]:
train_df = pd.read_csv('D:\\庫存健診開發\\data\\Clustering\\train_cluster.csv', index_col=0)
test_df = pd.read_csv('D:\\庫存健診開發\\data\\Clustering\\test_cluster.csv', index_col=0)

In [5]:
file_path = 'D:\\庫存健診開發\\data\\Training\\Raw\\'
func.ClusterSplit(train_df, test_df, data, file_path)

HBox(children=(IntProgress(value=0, max=9), HTML(value='')))

In [72]:
cluster = 4

In [73]:
data = pd.read_csv(f'D:\\庫存健診開發\\data\\Training\\Raw\\Cluster_{cluster}.csv', converters={'ts': str, 'StockNo': str, 'StockName': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,investment_buy_kurtosis,dealer_buy_skew,dealer_buy_kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
0,力山,1515,13.910575,14.208465,13.665561,13.952036,NaN,155621616.0,2004-02-11,9.536192e+06,...,NaN,NaN,NaN,NaN,NaN,0.542905,0.542905,0.000000,0.000000,0.000000
1,力山,1515,13.949125,14.245834,13.702850,13.987533,-0.55,63607869.0,2004-02-12,3.492422e+06,...,NaN,NaN,NaN,9678.440283,NaN,0.542985,0.542947,0.000000,0.000000,0.000000
2,力山,1515,13.989035,14.284522,13.741454,14.024281,0.10,31288311.0,2004-02-13,1.849317e+06,...,NaN,NaN,NaN,5291.084887,14969.525170,0.543068,0.542993,0.000000,0.000000,0.000000
3,力山,1515,14.030399,14.324618,13.781463,14.062367,0.00,24792180.0,2004-02-16,2.210693e+06,...,NaN,NaN,NaN,6536.671907,11827.756793,0.543155,0.543042,0.000000,0.000000,0.000000
4,力山,1515,14.072245,14.365181,13.821939,14.100897,0.25,59155365.0,2004-02-17,4.368961e+06,...,NaN,NaN,NaN,13030.568498,19567.240404,0.543242,0.543093,0.000000,0.581292,0.300022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221425,慶豐富,9935,33.575285,34.281237,33.197161,33.869192,0.75,67434810.0,2019-09-17,2.300861e+06,...,-3.0,-0.385581,1.891185,16339.059743,25271.736409,1.084076,1.150115,0.881271,0.641703,0.619177
221426,慶豐富,9935,33.864569,34.635303,33.460344,34.134298,0.15,113411083.0,2019-09-18,1.906408e+06,...,-3.0,-0.378950,1.891297,16425.585669,32764.645412,1.174959,1.153221,0.901992,0.618237,0.618707
221427,慶豐富,9935,34.051103,34.866122,33.636676,34.316068,0.30,56019457.0,2019-09-19,1.813187e+06,...,-3.0,-0.378950,1.891297,9987.497883,26413.083552,1.229446,1.162749,0.913269,0.597376,0.608042
221428,慶豐富,9935,34.145328,34.985166,33.735694,34.424537,-0.80,71396408.0,2019-09-20,1.988748e+06,...,-3.0,-0.364387,1.944431,5503.157420,15490.655303,1.249473,1.173589,0.918778,0.582272,0.595157
221429,慶豐富,9935,34.182747,35.038777,33.784423,34.484240,-0.55,64260442.0,2019-09-23,2.253656e+06,...,-3.0,-0.575831,3.134664,2469.716931,7972.874351,1.254354,1.183685,0.921349,0.535174,0.565166

In [74]:
train_df, val_df, test_df = func.TrainTestSplit(data, date(2016,1,1), date(2017,9,1))

In [75]:
feature_list = ['close', 'high', 'low', 'open',
       'vol', 'VWAP', 
       'ma7', 'ma21', '26ema', '12ema', 'MACD', 'upper_band', 'lower_band',
       'close_skew', 'close_kurtosis', 'pvt', 'ATR', 'RSI_15', 'SO%k5', 'SO%d3', 'foreign_buy',
       'investment_buy', 'dealer_buy', 'foreign_buy_skew',
       'foreign_buy_kurtosis', 'investment_buy_skew',
       'investment_buy_kurtosis', 'dealer_buy_skew', 'dealer_buy_kurtosis']

print(train_df[feature_list].isna().values.any())
print(val_df[feature_list].isna().values.any())
print(test_df[feature_list].isna().values.any())

False
False
False

In [76]:
param = func.GetScalerParam(train_df, feature_list)
param

,max,min,std,mean
close,2.793725e+02,8.678434e-01,2.426516e+01,2.442173e+01
high,2.885206e+02,8.803965e-01,2.480393e+01,2.490888e+01
low,2.749601e+02,8.567398e-01,2.386543e+01,2.405551e+01
open,2.788344e+02,8.695248e-01,2.434476e+01,2.448895e+01
vol,1.219272e+08,-8.841494e+06,4.205721e+06,2.082543e+06
VWAP,2.797775e+02,0.000000e+00,2.434992e+01,2.445469e+01
ma7,2.723521e+02,8.720029e-01,2.429854e+01,2.445759e+01
ma21,2.681994e+02,9.067116e-01,2.435978e+01,2.454085e+01
26ema,2.659416e+02,9.564015e-01,2.432042e+01,2.456825e+01
12ema,2.707272e+02,8.987936e-01,2.430311e+01,2.448723e+01
MACD,1.978479e+01,-1.432503e+01,1.149214e+00,-8.101314e-02
upper_band,2.872818e+02,9.704419e-01,2.624447e+01,2.593667e+01
lower_band,2.584328e+02,-7.206238e-01,2.260735e+01,2.314503e+01
close_skew,4.128965e+00,-4.067776e+00,5.973963e-01,1.112635e-02
close_kurtosis,1.504994e+01,-1.999391e+00,7.155984e-01,-8.706205e-01
pvt,5.869777e+06,-2.355541e+06,8.423737e+04,5.158603e+03
ATR,1.823125e+01,2.227546e-02,1.030790e+00,8.639257e-01
RSI_15,1.000000e+00,0.000000e+00,4.276053e-01,4.623839e-01
SO%k5,2.296677e+00,-1.017248e+00,1.915458e-01,4.372568e-01
SO%d3,1.214363e+00,-7.127149e-01,1.879291e-01,4.372485e-01
foreign_buy,2.592500e+04,-2.455800e+04,3.698097e+02,-2.273374e+00
investment_buy,2.420900e+04,-2.061200e+04,2.717913e+02,-1.526657e+00
dealer_buy,8.327000e+03,-5.344000e+03,1.377996e+02,-8.291159e-01
foreign_buy_skew,4.129483e+00,-4.129483e+00,1.633940e+00,-1.787200e-02
foreign_buy_kurtosis,1.505263e+01,-3.000000e+00,3.998913e+00,2.972212e+00
investment_buy_skew,4.129483e+00,-4.129483e+00,1.785257e+00,-1.325590e-01
investment_buy_kurtosis,1.505263e+01,-3.000000e+00,6.171946e+00,1.217094e+00
dealer_buy_skew,4.129483e+00,-4.129483e+00,1.731677e+00,-1.017547e-01
dealer_buy_kurtosis,1.505263e+01,-3.000000e+00,4.511625e+00,3.594092e+00

In [77]:
train_df, val_df, test_df = func.Scaler(train_df, feature_list, param), func.Scaler(val_df, feature_list, param), func.Scaler(test_df, feature_list, param)
display(train_df)
display(test_df)

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,investment_buy_kurtosis,dealer_buy_skew,dealer_buy_kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
24,力山,1515,0.047477,0.046809,0.047344,0.047541,-0.40,25123194.0,2004-03-16,0.091029,...,0.273285,0.990898,0.977669,-4703.215255,0.285346,0.510565,0.027556,0.201988,0.434103,0.589784
25,力山,1515,0.047400,0.046726,0.047267,0.047461,-0.30,46131748.0,2004-03-17,0.092463,...,0.274384,0.990898,0.977669,-4937.272050,0.285205,0.507864,0.027442,0.169743,0.435059,0.589955
26,力山,1515,0.047316,0.046636,0.047182,0.047373,0.15,29344271.0,2004-03-18,0.094398,...,0.274384,0.990178,0.975964,-5857.267911,0.285065,0.505059,0.027322,0.141421,0.435274,0.590226
27,力山,1515,0.047223,0.046536,0.047089,0.047276,-0.05,23819413.0,2004-03-19,0.093965,...,0.275172,0.990178,0.975983,-6363.994193,0.284891,0.502138,0.027198,0.116878,0.434493,0.589690
28,力山,1515,0.047130,0.046438,0.046996,0.047180,-1.00,5886383.0,2004-03-22,0.094861,...,0.275172,0.990178,0.975983,-6548.556143,0.284807,0.499199,0.027070,0.097637,0.434041,0.589033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176206,羅昇,8374,0.032165,0.031599,0.032081,0.031988,0.05,437976.0,2015-12-25,0.067879,...,0.000000,0.177119,0.449304,-95.660073,0.286367,0.319329,0.019257,0.000002,0.415275,0.549489
176207,羅昇,8374,0.032086,0.031508,0.032008,0.031901,0.00,317815.0,2015-12-28,0.067797,...,0.000000,0.177119,0.449304,-54.069585,0.286359,0.312957,0.018845,0.000002,0.421913,0.558504
176208,羅昇,8374,0.032015,0.031424,0.031944,0.031824,-0.20,193670.0,2015-12-29,0.067889,...,0.000000,0.177119,0.449304,-73.327304,0.286361,0.306400,0.018440,0.000002,0.427914,0.568172
176209,羅昇,8374,0.031950,0.031347,0.031889,0.031755,0.00,344050.0,2015-12-30,0.067911,...,0.000000,0.721062,0.553936,-71.546690,0.286359,0.299635,0.018039,0.000002,0.432544,0.576987
176210,羅昇,8374,0.031905,0.031294,0.031854,0.031712,-0.05,231050.0,2015-12-31,0.067935,...,0.000000,0.721062,0.553936,-55.187789,0.286362,0.293688,0.017647,0.000002,0.437711,0.585837

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,investment_buy_kurtosis,dealer_buy_skew,dealer_buy_kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
176617,中和,1439,0.071569,0.070366,0.072245,0.072067,0.10,1164079.0,2017-09-01,0.068107,...,0.0,0.115872,0.655258,-2828.916168,0.286032,1.089978,0.032721,0.050083,0.338770,0.543333
176618,中和,1439,0.071364,0.070121,0.072029,0.071806,0.00,697000.0,2017-09-04,0.068009,...,0.0,0.115872,0.655258,-142.058268,0.286016,0.449872,0.031566,0.046332,0.338072,0.483337
176619,中和,1439,0.071155,0.069865,0.071806,0.071528,-0.20,636317.0,2017-09-05,0.068104,...,0.0,0.115872,0.655258,-181.040224,0.286338,0.437559,0.030471,0.042558,0.337382,0.452746
176620,中和,1439,0.070944,0.069602,0.071578,0.071235,-0.10,1565523.0,2017-09-06,0.068298,...,0.0,0.000000,1.000000,-254.879504,0.286324,0.424291,0.029422,0.038873,0.336866,0.437007
176621,中和,1439,0.070656,0.069250,0.071272,0.070849,-0.50,2544802.0,2017-09-07,0.068437,...,0.0,0.000000,1.000000,-420.120139,0.286295,0.406904,0.028385,0.034311,0.370526,0.458079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221425,慶豐富,9935,0.117439,0.116120,0.117986,0.118719,0.75,67434810.0,2019-09-17,0.085207,...,0.0,0.453314,0.270940,16339.059743,0.289449,1.084076,0.061939,0.881271,0.500600,0.691146
221426,慶豐富,9935,0.118478,0.117351,0.118946,0.119673,0.15,113411083.0,2019-09-18,0.082190,...,0.0,0.454117,0.270946,16425.585669,0.290360,1.174959,0.062109,0.901992,0.493519,0.690902
221427,慶豐富,9935,0.119148,0.118154,0.119590,0.120326,0.30,56019457.0,2019-09-19,0.081477,...,0.0,0.454117,0.270946,9987.497883,0.289588,1.229446,0.062632,0.913269,0.487224,0.685368
221428,慶豐富,9935,0.119486,0.118567,0.119951,0.120717,-0.80,71396408.0,2019-09-20,0.082820,...,0.0,0.455880,0.273890,5503.157420,0.288260,1.249473,0.063228,0.918778,0.482666,0.678682
221429,慶豐富,9935,0.119621,0.118754,0.120129,0.120932,-0.55,64260442.0,2019-09-23,0.084846,...,0.0,0.430278,0.339821,2469.716931,0.287346,1.254354,0.063782,0.921349,0.468454,0.663118

In [78]:
df_list = [group[1] for group in train_df.groupby(train_df['StockNo'])]

X_train, Y_train = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_elimination, lookback=20, forward=5, feature_list=feature_list), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_train.append(xx.tolist())
            Y_train.extend(x[1])

np.array(X_train).shape

HBox(children=(IntProgress(value=0, max=75), HTML(value='')))

(140861, 20, 29)

In [79]:
df_list = [group[1] for group in val_df.groupby(val_df['StockNo'])]

X_val, Y_val = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_elimination, lookback=20, forward=5, feature_list=feature_list), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_val.append(xx.tolist())
            Y_val.extend(x[1])

np.array(X_val).shape

HBox(children=(IntProgress(value=0, max=83), HTML(value='')))

(29344, 20, 29)

In [80]:
df_list = [group[1] for group in test_df.groupby(test_df['StockNo'])]

X_test, Y_test = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.create_dataset, lookback=20, forward=5, feature_list=feature_list, problem='classification'), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_test.append(xx.tolist())
            Y_test.extend(x[1])

np.array(X_test).shape

HBox(children=(IntProgress(value=0, max=95), HTML(value='')))

(42049, 20, 29)

In [81]:
(len(X_train) == len(Y_train)) and (len(X_val) == len(Y_val)) and (len(X_test) == len(Y_test))

True

In [82]:
save_list = [X_train, Y_train, X_val, Y_val, X_test, Y_test]

In [83]:
import pickle
with open(f'D:\\庫存健診開發\\data\\Training\\processed\\DL\\Cluster_{cluster}_classification_minmax0_Weekly', 'wb') as fp:
    pickle.dump(save_list, fp)

In [84]:
train_df = func.transform_csv(X_train, Y_train, cluster, feature_list)
train_df

,close_day1,high_day1,low_day1,open_day1,vol_day1,VWAP_day1,ma7_day1,ma21_day1,26ema_day1,12ema_day1,...,foreign_buy_skew_day20,foreign_buy_kurtosis_day20,investment_buy_skew_day20,investment_buy_kurtosis_day20,dealer_buy_skew_day20,dealer_buy_kurtosis_day20,Y,ts,StockNo,cluster
0,0.097933,0.096677,0.098269,0.099098,0.070020,0.100614,0.103912,0.114814,0.113210,0.107371,...,0.715162,0.289900,0.5,0.0,0.181170,0.446727,0,2014-12-23,1592,4
1,0.097640,0.096332,0.097936,0.098704,0.068754,0.100293,0.102734,0.113615,0.112274,0.106325,...,0.710723,0.286807,0.5,0.0,0.015187,0.966926,0,2014-12-24,1592,4
2,0.097412,0.096047,0.097671,0.098369,0.069767,0.100033,0.101746,0.112468,0.111408,0.105408,...,0.710723,0.286807,0.5,0.0,0.924936,0.813296,0,2014-12-25,1592,4
3,0.097240,0.095814,0.097463,0.098085,0.068704,0.099822,0.100974,0.111371,0.110609,0.104608,...,0.709096,0.286578,0.5,0.0,0.896567,0.744924,1,2014-12-26,1592,4
4,0.097393,0.095905,0.097592,0.098107,0.069449,0.099938,0.100475,0.110330,0.109897,0.103957,...,0.708670,0.285472,0.5,0.0,0.756427,0.560750,1,2014-12-27,1592,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140856,0.029377,0.028871,0.029594,0.029569,0.069987,0.032387,0.030171,0.030424,0.030196,0.030211,...,0.483238,0.182231,0.5,0.0,0.490585,0.152467,0,2015-12-24,6235,4
140857,0.029349,0.028827,0.029569,0.029532,0.068581,0.032352,0.030156,0.030445,0.030220,0.030206,...,0.544517,0.174441,0.5,0.0,0.477399,0.146795,0,2015-12-25,6235,4
140858,0.029302,0.028768,0.029525,0.029478,0.068069,0.032300,0.030136,0.030462,0.030238,0.030194,...,0.560779,0.195683,0.5,0.0,0.477399,0.146795,0,2015-12-28,6235,4
140859,0.029237,0.028695,0.029462,0.029409,0.068360,0.032230,0.030106,0.030473,0.030250,0.030174,...,0.605897,0.211653,0.5,0.0,0.488066,0.133929,1,2015-12-29,6235,4
140860,0.029158,0.028609,0.029385,0.029326,0.068773,0.032147,0.030065,0.030475,0.030254,0.030144,...,0.603340,0.207022,0.5,0.0,0.488066,0.133929,0,2015-12-30,6235,4

In [85]:
val_df = func.transform_csv(X_val, Y_val, cluster, feature_list)
val_df

,close_day1,high_day1,low_day1,open_day1,vol_day1,VWAP_day1,ma7_day1,ma21_day1,26ema_day1,12ema_day1,...,foreign_buy_skew_day20,foreign_buy_kurtosis_day20,investment_buy_skew_day20,investment_buy_kurtosis_day20,dealer_buy_skew_day20,dealer_buy_kurtosis_day20,Y,ts,StockNo,cluster
0,0.036807,0.036535,0.036526,0.036775,0.084678,0.039758,0.036659,0.034866,0.034654,0.036025,...,0.277589,0.441750,0.5,0.0,0.580767,0.363015,0,2016-02-15,2314,4
1,0.037177,0.036912,0.036888,0.037149,0.085662,0.040129,0.037017,0.035183,0.034957,0.036368,...,0.270484,0.452963,0.5,0.0,0.580767,0.363015,0,2016-02-16,2314,4
2,0.037556,0.037297,0.037259,0.037530,0.090714,0.040508,0.037383,0.035506,0.035266,0.036719,...,0.284054,0.434554,0.5,0.0,0.581952,0.363404,0,2016-02-17,2314,4
3,0.037943,0.037690,0.037638,0.037920,0.083396,0.040895,0.037757,0.035836,0.035583,0.037078,...,0.330656,0.370639,0.5,0.0,0.581080,0.364274,0,2016-02-18,2314,4
4,0.038279,0.038032,0.037967,0.038259,0.083342,0.041231,0.038131,0.036171,0.035903,0.037434,...,0.355191,0.342484,0.5,0.0,0.583926,0.364696,1,2016-02-19,2314,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29339,0.070628,0.069688,0.071504,0.071567,0.061197,0.073803,0.071919,0.071610,0.071539,0.071784,...,0.698070,0.399747,0.5,0.0,0.088753,0.791766,1,2017-08-24,8374,4
29340,0.071016,0.070083,0.071910,0.071989,0.060928,0.074199,0.072122,0.071787,0.071744,0.072000,...,0.655091,0.295514,0.5,0.0,0.094082,0.781494,0,2017-08-25,8374,4
29341,0.071642,0.070726,0.072498,0.072599,0.063141,0.074823,0.072393,0.071990,0.071982,0.072282,...,0.378528,0.370572,0.5,0.0,0.093541,0.783880,0,2017-08-28,8374,4
29342,0.072410,0.071517,0.073196,0.073325,0.065650,0.075585,0.072755,0.072227,0.072263,0.072642,...,0.384320,0.361614,0.5,0.0,0.093157,0.785845,1,2017-08-29,8374,4
29343,0.073383,0.072521,0.074054,0.074214,0.068903,0.076544,0.073236,0.072508,0.072598,0.073101,...,0.380141,0.338721,0.5,0.0,0.092258,0.789071,1,2017-08-30,8374,4

In [86]:
test_df = func.transform_csv(X_test, Y_test, cluster, feature_list)
test_df

,close_day1,high_day1,low_day1,open_day1,vol_day1,VWAP_day1,ma7_day1,ma21_day1,26ema_day1,12ema_day1,...,foreign_buy_skew_day20,foreign_buy_kurtosis_day20,investment_buy_skew_day20,investment_buy_kurtosis_day20,dealer_buy_skew_day20,dealer_buy_kurtosis_day20,Y,ts,StockNo,cluster
0,0.198640,0.195237,0.198482,0.197730,0.070977,0.200649,0.197447,0.199565,0.202040,0.198485,...,0.637346,0.343268,0.625474,0.157460,0.382494,0.212158,1,2018-04-12,1760,4
1,0.204011,0.200831,0.202978,0.202557,0.072577,0.205722,0.199348,0.199723,0.203072,0.200351,...,0.612884,0.300003,0.625474,0.157460,0.386034,0.208682,0,2018-04-13,1760,4
2,0.209429,0.206172,0.207290,0.207031,0.073653,0.210634,0.202053,0.200316,0.204486,0.202793,...,0.589231,0.249489,0.624639,0.156709,0.395432,0.209244,0,2018-04-16,1760,4
3,0.214735,0.210991,0.211213,0.210878,0.073925,0.215165,0.205566,0.201297,0.206235,0.205702,...,0.584196,0.246123,0.590892,0.152247,0.394233,0.207344,0,2018-04-17,1760,4
4,0.221110,0.216836,0.215863,0.215498,0.073852,0.220599,0.210114,0.202676,0.208378,0.209176,...,0.909090,0.783642,0.548446,0.150030,0.395112,0.207697,0,2018-04-18,1760,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42044,0.096568,0.095632,0.095341,0.095714,0.111265,0.099136,0.097260,0.093187,0.094633,0.095963,...,0.533602,0.131960,0.500000,0.000000,0.414594,0.278187,1,2019-09-16,9935,4
42045,0.096963,0.095846,0.095929,0.096276,0.108438,0.099471,0.097883,0.093861,0.095147,0.096579,...,0.530223,0.134494,0.500000,0.000000,0.402893,0.295041,1,2019-09-17,9935,4
42046,0.097253,0.095910,0.096473,0.096785,0.082974,0.099693,0.098416,0.094544,0.095646,0.097146,...,0.533925,0.134149,0.500000,0.000000,0.419722,0.283085,1,2019-09-18,9935,4
42047,0.098077,0.096616,0.097439,0.097733,0.083525,0.100489,0.098968,0.095238,0.096172,0.097757,...,0.541346,0.131663,0.500000,0.000000,0.430532,0.301622,1,2019-09-19,9935,4
42048,0.099482,0.098018,0.098862,0.099158,0.090943,0.101908,0.099629,0.095978,0.096768,0.098497,...,0.548765,0.127634,0.500000,0.000000,0.437699,0.295606,1,2019-09-20,9935,4

In [87]:
train_df.isna().values.any()
val_df.isna().values.any()
test_df.isna().values.any()

False

In [88]:
train_df.to_csv(f'D:\\庫存健診開發\\data\\Training\\processed\\AutoML\\train_{cluster}.csv', index=False)
val_df.to_csv(f'D:\\庫存健診開發\\data\\Training\\processed\\AutoML\\val_{cluster}.csv', index=False)
test_df.to_csv(f'D:\\庫存健診開發\\data\\Training\\processed\\AutoML\\test_{cluster}.csv', index=False)