In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import datetime, timedelta, date
from tqdm import tqdm_notebook as tqdm
import seaborn as sns

from multiprocessing import Pool
from functools import partial
import Training_function as func

In [2]:
data = pd.read_csv('D:\\庫存健診開發\\data\\Stock\\TWSE_Stock_feature.csv', converters={'ts': str, 'StockNo': str, 'StockName': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,investment_buy_kurtosis,dealer_buy_skew,dealer_buy_kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
0,亞泥,1102,23.869740,24.366515,23.277261,23.766541,NaN,1.895267e+08,2004-02-11,1.953132e+07,...,NaN,NaN,NaN,NaN,NaN,1.089254,1.089254,0.000000,0.000000,0.000000
1,亞泥,1102,23.900024,24.396603,23.318646,23.805446,-0.50,2.468034e+08,2004-02-12,9.896328e+06,...,NaN,NaN,NaN,12555.716747,NaN,1.077957,1.083229,0.000000,0.000000,0.000000
2,亞泥,1102,23.931360,24.427742,23.361480,23.845723,1.40,8.446286e+08,2004-02-13,2.937028e+07,...,NaN,NaN,NaN,38508.350723,51064.067470,1.066261,1.076803,0.000000,0.000000,0.000000
3,亞泥,1102,23.963821,24.460004,23.405864,23.887465,0.40,1.132873e+09,2004-02-16,3.486248e+07,...,NaN,NaN,NaN,47288.042327,85796.393050,1.054141,1.069958,0.000000,0.000000,0.000000
4,亞泥,1102,23.996646,24.492628,23.450749,23.929679,0.80,6.549583e+08,2004-02-17,3.180797e+07,...,NaN,NaN,NaN,43568.844907,90856.887234,1.041878,1.062752,0.000000,0.591908,0.305501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870369,潤泰新,9945,42.597097,42.882676,42.478737,42.769965,0.00,4.273570e+07,2019-09-17,9.913275e+05,...,14.891503,0.774622,-0.069637,-2939.578552,-5810.041361,0.403939,0.446959,0.394791,0.173960,0.230880
2870370,潤泰新,9945,42.508437,42.815835,42.407700,42.711107,-0.30,6.837791e+07,2019-09-18,1.560745e+06,...,14.379924,0.959324,0.222628,-3248.485107,-6188.063659,0.408136,0.442106,0.347899,0.146203,0.188541
2870371,潤泰新,9945,42.456466,42.772982,42.365112,42.673485,-0.55,5.453982e+07,2019-09-19,1.289888e+06,...,14.379924,0.959324,0.222628,-1577.016568,-4825.501675,0.407870,0.437827,0.321718,0.133362,0.160952
2870372,潤泰新,9945,42.423662,42.743618,42.336151,42.646875,-0.50,1.163660e+08,2019-09-20,2.742475e+06,...,7.977569,0.946702,0.183959,-2119.021081,-3696.037649,0.407467,0.434032,0.303942,0.137104,0.149028
2870373,潤泰新,9945,42.425955,42.738238,42.333337,42.641086,-0.15,7.036625e+07,2019-09-23,1.604318e+06,...,13.563851,1.080792,0.370129,86.744902,-2032.276179,0.404901,0.430391,0.302088,0.168600,0.158814

In [4]:
train_df = pd.read_csv('D:\\庫存健診開發\\data\\Clustering\\train_cluster.csv', index_col=0)
test_df = pd.read_csv('D:\\庫存健診開發\\data\\Clustering\\test_cluster.csv', index_col=0)

In [5]:
file_path = 'D:\\庫存健診開發\\data\\Training\\Raw\\'
func.ClusterSplit(train_df, test_df, data, file_path)

HBox(children=(IntProgress(value=0, max=9), HTML(value='')))

In [6]:
cluster = 0

In [7]:
data = pd.read_csv(f'D:\\庫存健診開發\\data\\Training\\Raw\\Cluster_{cluster}.csv', converters={'ts': str, 'StockNo': str, 'StockName': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,investment_buy_kurtosis,dealer_buy_skew,dealer_buy_kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
0,亞泥,1102,23.869740,24.366515,23.277261,23.766541,NaN,1.895267e+08,2004-02-11,1.953132e+07,...,NaN,NaN,NaN,NaN,NaN,1.089254,1.089254,0.000000,0.000000,0.000000
1,亞泥,1102,23.900024,24.396603,23.318646,23.805446,-0.5,2.468034e+08,2004-02-12,9.896328e+06,...,NaN,NaN,NaN,12555.716747,NaN,1.077957,1.083229,0.000000,0.000000,0.000000
2,亞泥,1102,23.931360,24.427742,23.361480,23.845723,1.4,8.446286e+08,2004-02-13,2.937028e+07,...,NaN,NaN,NaN,38508.350723,51064.067470,1.066261,1.076803,0.000000,0.000000,0.000000
3,亞泥,1102,23.963821,24.460004,23.405864,23.887465,0.4,1.132873e+09,2004-02-16,3.486248e+07,...,NaN,NaN,NaN,47288.042327,85796.393050,1.054141,1.069958,0.000000,0.000000,0.000000
4,亞泥,1102,23.996646,24.492628,23.450749,23.929679,0.8,6.549583e+08,2004-02-17,3.180797e+07,...,NaN,NaN,NaN,43568.844907,90856.887234,1.041878,1.062752,0.000000,0.591908,0.305501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262674,豐泰,9910,212.664249,215.452195,211.104309,212.621361,1.5,1.365693e+08,2019-09-17,1.587933e+06,...,5.156342,1.055711,0.814090,-4922.734473,-5698.862772,4.347886,4.092430,0.843744,0.559036,0.653585
262675,豐泰,9910,211.094301,213.994288,210.085503,211.051012,-2.0,4.263209e+08,2019-09-18,1.009538e+06,...,6.283943,0.933724,0.529445,-7452.694728,-12375.429201,3.908786,4.069474,0.743342,0.171682,0.412633
262676,豐泰,9910,210.585291,213.624853,209.860156,210.550065,-0.5,1.918511e+08,2019-09-19,9.299355e+05,...,6.687885,0.626960,0.421550,-2242.348658,-9695.043386,3.764697,4.031377,0.721635,0.118849,0.265741
262677,豐泰,9910,211.293958,214.514407,210.545322,211.305370,-1.0,4.088073e+08,2019-09-20,1.411221e+06,...,7.159388,0.486717,0.310809,4749.081522,2506.732864,3.969084,4.023591,0.754038,0.234999,0.250370
262678,豐泰,9910,211.967225,215.326795,211.180972,211.998248,0.5,1.974065e+08,2019-09-23,1.371041e+06,...,7.159990,0.292921,-0.142663,4368.680040,9117.761562,4.145823,4.038870,0.780684,0.376798,0.313584

In [8]:
train_df, val_df, test_df = func.TrainTestSplit(data, date(2016,1,1), date(2017,9,1))

D:\庫存健診開發\code\TrainingPrep\Training_function.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  train_df = data[data['ts'].dt.date < TrainDate][data['26ema'].notnull()]
D:\庫存健診開發\code\TrainingPrep\Training_function.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  val_df = data[data['ts'].dt.date < valDate][data['ts'].dt.date >= TrainDate][data['26ema'].notnull()]
D:\庫存健診開發\code\TrainingPrep\Training_function.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  test_df = data[data['ts'].dt.date >= valDate][data['26ema'].notnull()]

In [18]:
feature_list = ['close', 'high', 'low', 'open',
       'vol', 'VWAP', 'ma7', 'ma21', '26ema', '12ema', 'MACD', 'upper_band',
       'lower_band', 'close_skew', 'close_kurtosis', 'foreign_buy_skew',
       'foreign_buy_kurtosis', 'investment_buy_skew',
       'investment_buy_kurtosis', 'foreign_buy',
       'investment_buy', 'pvt', 'ATR',
       'RSI_15', 'SO%k5', 'SO%d3']

print(train_df[feature_list].isna().values.any())
print(val_df[feature_list].isna().values.any())
print(test_df[feature_list].isna().values.any())

False
False
False

In [19]:
param = func.GetScalerParam(train_df, feature_list)
param

                         max  min       std      mean
close                    1.0  0.0  0.046227  0.021977
high                     1.0  0.0  0.046098  0.021846
low                      1.0  0.0  0.045851  0.021842
open                     1.0  0.0  0.045852  0.021784
vol                      1.0  0.0  0.009978  0.131298
VWAP                     1.0  0.0  0.046012  0.022321
ma7                      1.0  0.0  0.046970  0.022350
ma21                     1.0  0.0  0.046938  0.022387
26ema                    1.0  0.0  0.047077  0.022494
12ema                    1.0  0.0  0.046953  0.022366
MACD                     1.0  0.0  0.016420  0.544133
upper_band               1.0  0.0  0.047974  0.022472
lower_band               1.0  0.0  0.043905  0.041331
close_skew               1.0  0.0  0.073283  0.497412
close_kurtosis           1.0  0.0  0.044129  0.067865
foreign_buy_skew         1.0  0.0  0.127494  0.502442
foreign_buy_kurtosis     1.0  0.0  0.129934  0.171600
investment_buy_skew      1.0  0.0  0.221415  0.479768
investment_buy_kurtosis  1.0  0.0  0.214799  0.360567
foreign_buy              1.0  0.0  0.002897  0.311575
investment_buy           1.0  0.0  0.016101  0.377643
pvt                      1.0  0.0  0.009512  0.207436
ATR                      1.0  0.0  0.031961  0.011709
RSI_15                   1.0  0.0  0.411680  0.520510
SO%k5                    1.0  0.0  0.101016  0.439266
SO%d3                    1.0  0.0  0.137854  0.434020

In [20]:
train_df, val_df, test_df = func.Scaler(train_df, feature_list, param), func.Scaler(val_df, feature_list, param), func.Scaler(test_df, feature_list, param)
display(train_df)
display(test_df)

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,investment_buy_kurtosis,dealer_buy_skew,dealer_buy_kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
24,亞泥,1102,0.006404,0.006406,0.006334,0.006349,-0.30,310866303.0,2004-03-16,0.133052,...,0.220487,0.562659,0.175023,-47902.399949,0.204056,0.895503,0.004854,0.045649,0.371058,0.341643
25,亞泥,1102,0.006385,0.006388,0.006316,0.006331,-1.30,346863303.0,2004-03-17,0.127142,...,0.221094,0.543455,0.168665,-18024.293974,0.205024,0.890688,0.004826,0.037261,0.368976,0.337770
26,亞泥,1102,0.006366,0.006368,0.006297,0.006313,0.80,289156687.0,2004-03-18,0.129164,...,0.218478,0.551826,0.175902,-30615.535921,0.205598,0.886101,0.004797,0.030431,0.366378,0.333983
27,亞泥,1102,0.006345,0.006348,0.006277,0.006293,-0.40,143443290.0,2004-03-19,0.130670,...,0.222268,0.533200,0.167519,-41708.513761,0.204811,0.881781,0.004770,0.024857,0.363099,0.329755
28,亞泥,1102,0.006323,0.006326,0.006257,0.006273,-1.70,5433306.0,2004-03-22,0.130375,...,0.222268,0.521607,0.173376,-41133.705304,0.204462,0.877431,0.004743,0.020461,0.360048,0.325467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229900,潤泰新,9945,0.011645,0.011583,0.011647,0.011603,0.20,61302162.0,2015-12-25,0.124882,...,0.201550,0.434866,0.137565,-10154.395200,0.206389,0.909170,0.004582,0.063797,0.260608,0.182050
229901,潤泰新,9945,0.011607,0.011547,0.011609,0.011568,-0.30,79530579.0,2015-12-28,0.124933,...,0.232735,0.410042,0.155507,-7170.656124,0.206638,0.913768,0.004604,0.057148,0.264367,0.183473
229902,潤泰新,9945,0.011579,0.011520,0.011580,0.011541,0.15,66482457.0,2015-12-29,0.124992,...,0.251072,0.416259,0.160307,-5621.219582,0.206788,0.918368,0.004627,0.052435,0.272674,0.190101
229903,潤泰新,9945,0.011567,0.011508,0.011567,0.011529,-0.50,110964914.0,2015-12-30,0.125126,...,0.289704,0.406106,0.162511,-2667.593924,0.206938,0.922606,0.004649,0.050286,0.288881,0.204956
229904,潤泰新,9945,0.011555,0.011496,0.011554,0.011517,-0.40,122208750.0,2015-12-31,0.125310,...,0.287442,0.408440,0.161032,-3067.158340,0.207023,0.926409,0.004672,0.048007,0.304068,0.223200

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,investment_buy_kurtosis,dealer_buy_skew,dealer_buy_kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
230311,亞泥,1102,0.007530,0.007403,0.007535,0.007451,0.10,94790172.0,2017-09-01,0.125536,...,0.434701,0.598845,0.374637,100131.207017,0.210688,0.873443,0.001712,0.968014,0.668619,0.734614
230312,亞泥,1102,0.007525,0.007397,0.007529,0.007444,0.00,46852247.0,2017-09-04,0.124695,...,0.434547,0.596782,0.372631,-1123.134367,0.210502,0.289917,0.001662,0.944271,0.660374,0.741783
230313,亞泥,1102,0.007520,0.007391,0.007523,0.007438,0.00,100375245.0,2017-09-05,0.125640,...,0.434200,0.583711,0.349731,-2153.200537,0.207104,0.288386,0.001617,0.918182,0.651841,0.739290
230314,亞泥,1102,0.007516,0.007384,0.007517,0.007431,-0.25,88723794.0,2017-09-06,0.125280,...,0.627707,0.571609,0.351091,-1614.047005,0.207088,0.287165,0.001577,0.890237,0.643318,0.731974
230315,亞泥,1102,0.007510,0.007376,0.007509,0.007422,-0.10,73188947.0,2017-09-07,0.125237,...,0.628893,0.585759,0.408987,-2318.861314,0.207083,0.285138,0.001540,0.849463,0.461555,0.598868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262674,豐泰,9910,0.061661,0.061214,0.061624,0.061019,1.50,136569295.0,2019-09-17,0.124565,...,0.451809,0.627826,0.211276,-4922.734473,0.207024,4.347886,0.022332,0.843744,0.478333,0.563575
262675,豐泰,9910,0.061203,0.060796,0.061324,0.060565,-2.00,426320900.0,2019-09-18,0.124270,...,0.514271,0.613056,0.195509,-7452.694728,0.206802,3.908786,0.022205,0.743342,0.265732,0.375207
262676,豐泰,9910,0.061054,0.060691,0.061258,0.060420,-0.50,191851142.0,2019-09-19,0.124229,...,0.536647,0.575913,0.189532,-2242.348658,0.206891,3.764697,0.021994,0.721635,0.236734,0.260372
262677,豐泰,9910,0.061261,0.060945,0.061459,0.060639,-1.00,408807276.0,2019-09-20,0.124475,...,0.562765,0.558932,0.183398,4749.081522,0.207297,3.969084,0.021951,0.754038,0.300483,0.248355
262678,豐泰,9910,0.061458,0.061178,0.061646,0.060839,0.50,197406460.0,2019-09-23,0.124454,...,0.562798,0.535467,0.158278,4368.680040,0.207516,4.145823,0.022035,0.780684,0.378311,0.297774

In [21]:
df_list = [group[1] for group in train_df.groupby(train_df['StockNo'])]

X_train, Y_train = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_elimination, lookback=20, forward=5, feature_list=feature_list), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_train.append(xx.tolist())
            Y_train.extend(x[1])

np.array(X_train).shape

HBox(children=(IntProgress(value=0, max=72), HTML(value='')))

(197067, 20, 26)

In [22]:
df_list = [group[1] for group in val_df.groupby(val_df['StockNo'])]

X_val, Y_val = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_elimination, lookback=20, forward=5, feature_list=feature_list), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_val.append(xx.tolist())
            Y_val.extend(x[1])

np.array(X_val).shape

HBox(children=(IntProgress(value=0, max=73), HTML(value='')))

(27592, 20, 26)

In [23]:
df_list = [group[1] for group in test_df.groupby(test_df['StockNo'])]

X_test, Y_test = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.create_dataset, lookback=20, forward=5, feature_list=feature_list, problem='classification'), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_test.append(xx.tolist())
            Y_test.extend(x[1])

np.array(X_test).shape

HBox(children=(IntProgress(value=0, max=65), HTML(value='')))

(30695, 20, 26)

In [24]:
(len(X_train) == len(Y_train)) and (len(X_val) == len(Y_val)) and (len(X_test) == len(Y_test))

True

In [25]:
save_list = [X_train, Y_train, X_val, Y_val, X_test, Y_test]

In [26]:
import pickle
with open(f'D:\\庫存健診開發\\data\\Training\\processed\\Cluster_{cluster}_classification_minmax0_Weekly', 'wb') as fp:
    pickle.dump(save_list, fp)