In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import datetime, timedelta, date
from tqdm import tqdm_notebook as tqdm
import seaborn as sns

from multiprocessing import Pool
from functools import partial
import Training_function as func

In [21]:
data = pd.read_csv('D:\\庫存健診開發\\data\\Stock\\TWSE_Stock_feature_log.csv', converters={'ts': str, 'StockNo': str, 'StockName': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,lower_band,skew,kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
0,嘉泥,1103,3.054602,3.081172,3.039477,3.062498,NaN,333925503.0,2004-02-11,16.352479,...,NaN,NaN,NaN,NaN,NaN,0.041694,0.041694,0.000000,0.000000,0.000000
1,嘉泥,1103,3.054331,3.080633,3.039346,3.062220,-0.90,246048766.0,2004-02-12,16.340381,...,NaN,NaN,NaN,-0.001451,NaN,0.041286,0.041477,0.000000,0.000000,0.000000
2,嘉泥,1103,3.054052,3.080077,3.039213,3.061934,0.40,333309529.0,2004-02-13,16.327849,...,NaN,NaN,NaN,-0.001491,-0.002942,0.040864,0.041245,0.000000,0.000000,0.000000
3,嘉泥,1103,3.053765,3.079502,3.039076,3.061640,1.00,515700813.0,2004-02-16,16.314851,...,NaN,NaN,NaN,-0.001533,-0.003024,0.040426,0.040997,0.000000,0.000000,0.000000
4,嘉泥,1103,3.053474,3.078921,3.038938,3.061342,-0.10,333141524.0,2004-02-17,16.301702,...,NaN,NaN,NaN,-0.001550,-0.003083,0.039983,0.040737,0.000000,0.344183,0.177643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870369,佳龍,9955,2.967179,2.979450,2.960362,2.972033,-0.20,10570940.0,2019-09-17,13.502837,...,2.967962,-0.558865,-0.907656,-0.034107,-0.066696,0.019089,0.024738,0.059349,0.124392,0.117789
2870370,佳龍,9955,2.959344,2.968882,2.951687,2.961290,-0.15,8499084.0,2019-09-18,13.339974,...,2.959696,-0.520054,-0.949418,-0.035223,-0.069330,0.017195,0.023795,0.048550,0.139673,0.128731
2870371,佳龍,9955,2.953398,2.961098,2.945143,2.953369,-0.35,18002738.0,2019-09-19,13.222699,...,2.951673,-0.477384,-1.036020,-0.026570,-0.061794,0.015955,0.022815,0.041966,0.156701,0.142716
2870372,佳龍,9955,2.949554,2.956317,2.940942,2.948448,0.35,10280286.0,2019-09-20,13.152947,...,2.944156,-0.405219,-1.162565,-0.017119,-0.043690,0.015375,0.021885,0.038169,0.178432,0.160574
2870373,佳龍,9955,2.946840,2.953072,2.938003,2.945145,0.15,8065152.0,2019-09-23,13.105957,...,2.937476,-0.313513,-1.292763,-0.012058,-0.029178,0.015069,0.021033,0.035594,0.213208,0.186891

In [3]:
train_df = pd.read_csv('D:\\庫存健診開發\\data\\Clustering\\train_cluster.csv', index_col=0)
test_df = pd.read_csv('D:\\庫存健診開發\\data\\Clustering\\test_cluster.csv', index_col=0)

In [4]:
file_path = 'D:\\庫存健診開發\\data\\Training\\Raw\\log\\'
func.ClusterSplit(train_df, test_df, data, file_path)

HBox(children=(IntProgress(value=0, max=9), HTML(value='')))

In [5]:
data = pd.read_csv('D:\\庫存健診開發\\data\\Training\\Raw\\log\\Cluster_0.csv', converters={'ts': str, 'StockNo': str, 'StockName': str})
data['ts'] = pd.to_datetime(data['ts'])
data

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,lower_band,skew,kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
0,亞泥,1102,3.175197,3.196191,3.149826,3.170833,NaN,1.895267e+08,2004-02-11,16.494601,...,NaN,NaN,NaN,NaN,NaN,0.046365,0.046365,0.000000,0.000000,0.000000
1,亞泥,1102,3.176629,3.197599,3.151780,3.172642,-0.5,2.468034e+08,2004-02-12,16.477809,...,NaN,NaN,NaN,0.007429,NaN,0.045819,0.046074,0.000000,0.000000,0.000000
2,亞泥,1102,3.178111,3.199057,3.153803,3.174514,1.4,8.446286e+08,2004-02-13,16.460400,...,NaN,NaN,NaN,0.007681,0.015110,0.045253,0.045763,0.000000,0.000000,0.000000
3,亞泥,1102,3.179648,3.200568,3.155901,3.176456,0.4,1.132873e+09,2004-02-16,16.442329,...,NaN,NaN,NaN,0.007949,0.015630,0.044667,0.045432,0.000000,0.000000,0.000000
4,亞泥,1102,3.181202,3.202097,3.158023,3.178420,0.8,6.549583e+08,2004-02-17,16.424050,...,NaN,NaN,NaN,0.008030,0.015979,0.044074,0.045084,0.000000,0.600264,0.309814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262674,豐泰,9910,5.355216,5.367650,5.348903,5.354940,1.5,1.365693e+08,2019-09-17,14.029725,...,5.273829,0.241913,-1.546393,0.003922,0.011698,0.018746,0.018722,0.861324,0.558318,0.612586
262675,豐泰,9910,5.355860,5.369960,5.350181,5.355581,-2.0,4.263209e+08,2019-09-18,14.056967,...,5.273580,0.084324,-1.647707,0.001689,0.005611,0.019779,0.018854,0.871221,0.514449,0.563517
262676,豐泰,9910,5.356946,5.372188,5.351768,5.356717,-0.5,1.918511e+08,2019-09-19,14.076353,...,5.274292,-0.087632,-1.664262,0.002854,0.004543,0.020420,0.019050,0.880610,0.471873,0.517695
262677,豐泰,9910,5.358280,5.374078,5.353442,5.358118,-1.0,4.088073e+08,2019-09-20,14.084528,...,5.275929,-0.267425,-1.592533,0.003509,0.006363,0.020636,0.019248,0.888489,0.420056,0.468876
262678,豐泰,9910,5.359645,5.375824,5.355104,5.359611,0.5,1.974065e+08,2019-09-23,14.090698,...,5.278786,-0.455531,-1.416056,0.003589,0.007098,0.020720,0.019432,0.895755,0.399011,0.433943

In [6]:
train_df, val_df, test_df = func.TrainTestSplit(data, date(2016,1,1), date(2017,9,1))

D:\庫存健診開發\code\TrainingPrep\Training_function.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  train_df = data[data['ts'].dt.date < TrainDate][data['26ema'].notnull()]
D:\庫存健診開發\code\TrainingPrep\Training_function.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  val_df = data[data['ts'].dt.date < valDate][data['ts'].dt.date >= TrainDate][data['26ema'].notnull()]
D:\庫存健診開發\code\TrainingPrep\Training_function.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  test_df = data[data['ts'].dt.date >= valDate][data['26ema'].notnull()]

In [7]:
feature_list = ['close', 'high', 'low', 'open',
       'vol', 'VWAP', 'ma7', 'ma21', '26ema', '12ema', 'MACD', 'upper_band',
       'lower_band', 'skew', 'kurtosis', 'pvt', 'ATR',
       'RSI_15', 'SO%k5', 'SO%d3']

print(train_df[feature_list].isna().values.any())
print(val_df[feature_list].isna().values.any())
print(test_df[feature_list].isna().values.any())

False
False
False

In [8]:
param = func.GetScalerParam(train_df, feature_list)
param

                  max       min       std       mean
close        8.110313  0.479616  0.954178   3.762095
high         8.131812  0.495624  0.954464   3.775139
low          8.091030  0.461258  0.953817   3.750170
open         8.113248  0.475671  0.954179   3.763236
vol         18.965341  9.444098  1.217951  15.796371
VWAP         8.112020  0.478395  0.954126   3.762487
ma7          8.110039  0.479953  0.953754   3.761994
ma21         8.107350  0.481397  0.952653   3.761752
26ema        8.100344  0.490706  0.951756   3.761635
12ema        8.107696  0.482004  0.953249   3.761906
MACD         0.578581 -0.147410  0.020496   0.000272
upper_band   8.117398  0.484324  0.952551   3.788170
lower_band   8.102249  0.469271  0.953954   3.735334
skew         4.127856 -4.127538  0.524219  -0.002108
kurtosis    15.044154 -1.999926  0.565687  -0.949722
pvt         14.230040 -0.680339  0.061971   0.000094
ATR          0.293767  0.004385  0.009617   0.025018
RSI_15       1.000000  0.000000  0.460414   0.514935
SO%k5        0.987879  0.072813  0.154847   0.488769
SO%d3        0.955745  0.076718  0.154245   0.488755

In [9]:
train_df, val_df, test_df = func.Scaler(train_df, feature_list, param), func.Scaler(val_df, feature_list, param), func.Scaler(test_df, feature_list, param)
display(train_df)
display(test_df)

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,lower_band,skew,kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
24,亞泥,1102,0.350586,0.350950,0.350714,0.351000,-0.30,310866303.0,2004-03-16,0.704478,...,0.351986,0.403664,0.076149,-0.015290,0.043614,0.038422,0.121573,0.039014,0.304439,0.317929
25,亞泥,1102,0.350194,0.350558,0.350339,0.350626,-1.30,346863303.0,2004-03-17,0.703204,...,0.351511,0.416843,0.065966,-0.015296,0.043577,0.038287,0.121003,0.032425,0.303233,0.314575
26,亞泥,1102,0.349781,0.350146,0.349942,0.350229,0.80,289156687.0,2004-03-18,0.701942,...,0.351024,0.428185,0.058998,-0.016125,0.043521,0.038166,0.120455,0.026913,0.300435,0.311442
27,亞泥,1102,0.349344,0.349710,0.349519,0.349808,-0.40,143443290.0,2004-03-19,0.700696,...,0.350523,0.437630,0.054472,-0.017054,0.043403,0.038061,0.119932,0.022301,0.295569,0.307343
28,亞泥,1102,0.348906,0.349272,0.349096,0.349387,-1.70,5433306.0,2004-03-22,0.699427,...,0.350016,0.445670,0.051290,-0.017103,0.043338,0.037950,0.119428,0.018646,0.291396,0.303122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229900,潤泰新,9945,0.431267,0.430494,0.432380,0.431396,0.20,61302162.0,2015-12-25,0.624089,...,0.419065,0.522353,0.047350,0.019646,0.048491,0.022734,0.062972,0.999884,0.704327,0.729175
229901,潤泰新,9945,0.431776,0.431006,0.432892,0.431909,-0.30,79530579.0,2015-12-28,0.624397,...,0.419509,0.518627,0.045359,0.015854,0.048009,0.022747,0.063032,0.999896,0.692863,0.723001
229902,潤泰新,9945,0.432223,0.431457,0.433342,0.432361,0.15,66482457.0,2015-12-29,0.624677,...,0.420005,0.513391,0.042965,0.013930,0.047626,0.022758,0.063089,0.999906,0.675740,0.711002
229903,潤泰新,9945,0.432573,0.431810,0.433693,0.432714,-0.50,110964914.0,2015-12-30,0.624913,...,0.420559,0.506660,0.040481,0.010872,0.047292,0.022766,0.063143,0.999914,0.648502,0.690824
229904,潤泰新,9945,0.432896,0.432135,0.434018,0.433041,-0.40,122208750.0,2015-12-31,0.625139,...,0.421168,0.498925,0.038508,0.010042,0.047031,0.022771,0.063192,0.999920,0.623673,0.667812

,StockName,StockNo,close,high,low,open,return,total,ts,vol,...,lower_band,skew,kurtosis,pvt_current,pvt,TR,ATR,RSI_15,SO%k5,SO%d3
230311,亞泥,1102,0.370828,0.368995,0.372411,0.370944,0.10,94790172.0,2017-09-01,0.570135,...,0.366721,0.920463,0.800210,0.143130,0.055236,0.035589,0.034133,0.924495,0.913167,0.835167
230312,亞泥,1102,0.370748,0.368889,0.372312,0.370839,0.00,46852247.0,2017-09-04,0.565461,...,0.366272,0.797684,0.378832,-0.002748,0.055044,0.010613,0.032556,0.902782,0.897993,0.882767
230313,亞泥,1102,0.370671,0.368782,0.372212,0.370731,0.00,100375245.0,2017-09-05,0.560381,...,0.366000,0.725746,0.213990,-0.002617,0.045269,0.010565,0.031156,0.878866,0.883496,0.899021
230314,亞泥,1102,0.370600,0.368677,0.372112,0.370621,-0.25,88723794.0,2017-09-06,0.554949,...,0.365832,0.675362,0.128329,-0.002416,0.045291,0.010527,0.029914,0.853185,0.869986,0.900116
230315,亞泥,1102,0.370495,0.368532,0.371974,0.370473,-0.10,73188947.0,2017-09-07,0.547991,...,0.365746,0.636225,0.077617,-0.003554,0.045228,0.010463,0.028800,0.815604,0.499106,0.707621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262674,豐泰,9910,0.638946,0.638018,0.640602,0.638850,1.50,136569295.0,2019-09-17,0.481621,...,0.629447,0.529284,0.026609,0.003922,0.046413,0.018746,0.049541,0.861324,0.530568,0.609614
262675,豐泰,9910,0.639030,0.638321,0.640769,0.638934,-2.00,426320900.0,2019-09-18,0.484482,...,0.629415,0.510195,0.020665,0.001689,0.046005,0.019779,0.049998,0.871221,0.482627,0.553793
262676,豐泰,9910,0.639172,0.638612,0.640977,0.639083,-0.50,191851142.0,2019-09-19,0.486518,...,0.629508,0.489366,0.019694,0.002854,0.045933,0.020420,0.050674,0.880610,0.436100,0.501665
262677,豐泰,9910,0.639347,0.638860,0.641197,0.639266,-1.00,408807276.0,2019-09-20,0.487377,...,0.629722,0.467587,0.023902,0.003509,0.046055,0.020636,0.051360,0.888489,0.379474,0.446127
262678,豐泰,9910,0.639526,0.639088,0.641414,0.639462,0.50,197406460.0,2019-09-23,0.488025,...,0.630097,0.444801,0.034256,0.003589,0.046105,0.020720,0.051996,0.895755,0.356474,0.406387

In [10]:
df_list = [group[1] for group in train_df.groupby(train_df['StockNo'])]

X_train, Y_train = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_elimination, lookback=20, forward=5, feature_list=feature_list), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_train.append(xx.tolist())
            Y_train.extend(x[1])

np.array(X_train).shape

HBox(children=(IntProgress(value=0, max=72), HTML(value='')))

(197067, 20, 20)

In [27]:
df_list = [group[1] for group in val_df.groupby(val_df['StockNo'])]

X_val, Y_val = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.separate_elimination, lookback=20, forward=5, feature_list=feature_list), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_val.append(xx.tolist())
            Y_val.extend(x[1])

np.array(X_val).shape

HBox(children=(IntProgress(value=0, max=73), HTML(value='')))

(27592, 20, 20)

In [28]:
df_list = [group[1] for group in test_df.groupby(test_df['StockNo'])]

X_test, Y_test = [], []

if __name__ == '__main__':
    with Pool(processes=12) as pool:
        for i, x in enumerate(tqdm(pool.imap_unordered(partial(func.create_dataset, lookback=20, forward=5, feature_list=feature_list, problem='classification'), df_list), total=len(df_list)), 1):
            for xx in x[0]:
                X_test.append(xx.tolist())
            Y_test.extend(x[1])

np.array(X_test).shape

HBox(children=(IntProgress(value=0, max=65), HTML(value='')))

(30695, 20, 20)

In [29]:
(len(X_train) == len(Y_train)) and (len(X_val) == len(Y_val)) and (len(X_test) == len(Y_test))

True

In [30]:
save_list = [X_train, Y_train, X_val, Y_val, X_test, Y_test]

In [31]:
cluster = 0
import pickle
with open(f'D:\\庫存健診開發\\data\\Training\\processed\\Cluster_{cluster}_classification_minmax0_Weekly_log', 'wb') as fp:
    pickle.dump(save_list, fp)